
package com.oracle.xmlns.adf.svc.errors;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.1
 * 2023-01-31T18:30:48.874+11:00
 * Generated source version: 3.3.1
 */

@WebFault(name = "ServiceErrorMessage", targetNamespace = "http://xmlns.oracle.com/adf/svc/errors/")
public class ServiceException extends Exception {

    private com.oracle.xmlns.adf.svc.errors.ServiceErrorMessage serviceErrorMessage;

    public ServiceException() {
        super();
    }

    public ServiceException(String message) {
        super(message);
    }

    public ServiceException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, com.oracle.xmlns.adf.svc.errors.ServiceErrorMessage serviceErrorMessage) {
        super(message);
        this.serviceErrorMessage = serviceErrorMessage;
    }

    public ServiceException(String message, com.oracle.xmlns.adf.svc.errors.ServiceErrorMessage serviceErrorMessage, java.lang.Throwable cause) {
        super(message, cause);
        this.serviceErrorMessage = serviceErrorMessage;
    }

    public com.oracle.xmlns.adf.svc.errors.ServiceErrorMessage getFaultInfo() {
        return this.serviceErrorMessage;
    }
}
