<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models/>
  </ModelsRepository>
  <DataSourceRepository/>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="map_2_33_146">
          <Public val="map_2_33_146"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="738112" _time="84231" date="18//11//2021" time="23:23:51.8972030"/>
        </Header>
        <ReturnValueExpression/>
        <Resource>
          <Columns>
            <Column id="1" name="1_Source_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="2" name="1_Source_JSonJCreateSourceBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="3" name="4_Destination_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="4" name="4_Destination_JSonJCreatedestinationBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="5" name="2_Destination_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="6" name="2_Destination_XMLIoPtrDll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole val="3"/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="7" name="2_Destination_XMLEncoding_w_Dll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_ALPHA"/>
                <StoredAs val="2"/>
                <Size val="3"/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
          </Columns>
        </Resource>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <_TotalVariabls val="7"/>
            <_TotalVirtuals val="7"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Select Name="A">
                  <ASS/>
                  <Column val="1"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="B">
                  <ASS/>
                  <Column val="2"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="C">
                  <ASS/>
                  <Column val="3"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="D">
                  <ASS/>
                  <Column val="4"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Select Name="E">
                  <ASS/>
                  <Column val="5"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="F">
                  <ASS/>
                  <Column val="6"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="G">
                  <ASS/>
                  <Column val="7"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="1"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="2"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="3"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   JCreate   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="B"/>
                  <WithValue val="4"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   Begin ErrorMsg   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="5"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="7"/>
                  <ReturnValue/>
                  <Condition Exp="6"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="8"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="9"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="10"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="11"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="12"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="13"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="14"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="15"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   End ErrorMsg   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="17"/>
                  <ReturnValue/>
                  <Condition Exp="16"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="18"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="19"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="21"/>
                  <ReturnValue/>
                  <Condition Exp="20"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="22"/>
                  <ReturnValue/>
                  <Condition Exp="20"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition Exp="20"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="24"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="25"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="26"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="27"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="20"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="28"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="C"/>
                  <WithValue val="29"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="30"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-2********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="31"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="32"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   JCreate   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="B"/>
                  <WithValue val="33"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   Begin ErrorMsg   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="34"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="36"/>
                  <ReturnValue/>
                  <Condition Exp="35"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="37"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="38"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="39"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="40"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="41"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="42"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="43"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="44"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   End ErrorMsg   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="46"/>
                  <ReturnValue/>
                  <Condition Exp="45"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="47"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="2"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="48"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="50"/>
                  <ReturnValue/>
                  <Condition Exp="49"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="51"/>
                  <ReturnValue/>
                  <Condition Exp="49"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="52"/>
                  <ReturnValue/>
                  <Condition Exp="49"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="53"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="54"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="55"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="56"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="49"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="57"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="58"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-2********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-3********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="59"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="60"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   JCreate   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="B"/>
                  <WithValue val="61"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   Begin ErrorMsg   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="62"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="64"/>
                  <ReturnValue/>
                  <Condition Exp="63"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="65"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="66"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="67"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="68"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="69"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="70"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="71"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="72"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   End ErrorMsg   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="74"/>
                  <ReturnValue/>
                  <Condition Exp="73"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="75"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="3"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="76"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="78"/>
                  <ReturnValue/>
                  <Condition Exp="77"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="79"/>
                  <ReturnValue/>
                  <Condition Exp="77"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="80"/>
                  <ReturnValue/>
                  <Condition Exp="77"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="81"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="82"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="83"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="84"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="77"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="85"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-3********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="87"/>
                  <ReturnValue/>
                  <Condition Exp="86"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="SetParam('xmlErr',' ')"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="GetParam ('C.HTTP_Body')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="BlobSize(A)&gt;0 AND (GetParam('xpi_SourceJsonIsNotWellFormed') = NULL() or GetParam('xpi_SourceJsonIsNotWellFormed') &gt; 0 ) "/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="JCreate('com.magicsoftware.xpi.json.JsonParser','([BZ)V',A,SharedValGet('IB_NullifJSONSourceNonExistentTagValue'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',JCall(B,'getElementsCount','(Ljava/lang/String;Z)Ljava/lang/Integer;','Root','TRUE'LOG))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="JExceptionOccurred() "/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',0)"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="GetParam('xpi_SourceJsonIsNotWellFormed') = 0"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="SetParam('Error',465)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source Json is not well-formed.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="18">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="19">
            <ExpSyntax val="BlobSize(A)&gt;0 AND JExceptionOccurred()='FALSE'LOG AND GetParam('xpi_SourceJsonIsNotWellFormed') &gt; 0 "/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="20">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="21">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="22">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="23">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="24">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="25">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="26">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="27">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="28">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="29">
            <ExpSyntax val="BlobAddBom(C,1)"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="30">
            <ExpSyntax val="SetParam ('000000000002000000000033F.InputjsonPart',C)"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="31">
            <ExpSyntax val="GetParam ('C.HTTP_Body')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="32">
            <ExpSyntax val="BlobSize(A)&gt;0 AND (GetParam('xpi_SourceJsonIsNotWellFormed') = NULL() or GetParam('xpi_SourceJsonIsNotWellFormed') &gt; 0 ) "/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="33">
            <ExpSyntax val="JCreate('com.magicsoftware.xpi.json.JsonParser','([BZ)V',A,SharedValGet('IB_NullifJSONSourceNonExistentTagValue'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="34">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',JCall(B,'getElementsCount','(Ljava/lang/String;Z)Ljava/lang/Integer;','Root','TRUE'LOG))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="35">
            <ExpSyntax val="JExceptionOccurred() "/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="36">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',0)"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="37">
            <ExpSyntax val="GetParam('xpi_SourceJsonIsNotWellFormed') = 0"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="38">
            <ExpSyntax val="SetParam('Error',465)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="39">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source Json is not well-formed.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="40">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="41">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="42">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="43">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="44">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="45">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="46">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="47">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="48">
            <ExpSyntax val="BlobSize(A)&gt;0 AND JExceptionOccurred()='FALSE'LOG AND GetParam('xpi_SourceJsonIsNotWellFormed') &gt; 0 "/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="49">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="50">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="51">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="52">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="53">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="54">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="55">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="56">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="57">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="58">
            <ExpSyntax val="SetParam ('C.RequestXML',E)"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="59">
            <ExpSyntax val="GetParam ('C.HTTP_Body')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="60">
            <ExpSyntax val="BlobSize(A)&gt;0 AND (GetParam('xpi_SourceJsonIsNotWellFormed') = NULL() or GetParam('xpi_SourceJsonIsNotWellFormed') &gt; 0 ) "/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="61">
            <ExpSyntax val="JCreate('com.magicsoftware.xpi.json.JsonParser','([BZ)V',A,SharedValGet('IB_NullifJSONSourceNonExistentTagValue'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="62">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',JCall(B,'getElementsCount','(Ljava/lang/String;Z)Ljava/lang/Integer;','Root','TRUE'LOG))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="63">
            <ExpSyntax val="JExceptionOccurred() "/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="64">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',0)"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="65">
            <ExpSyntax val="GetParam('xpi_SourceJsonIsNotWellFormed') = 0"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="66">
            <ExpSyntax val="SetParam('Error',465)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="67">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source Json is not well-formed.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="68">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="69">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="70">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="71">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="72">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="73">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="74">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="75">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="76">
            <ExpSyntax val="BlobSize(A)&gt;0 AND JExceptionOccurred()='FALSE'LOG AND GetParam('xpi_SourceJsonIsNotWellFormed') &gt; 0 "/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="77">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="78">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="79">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="80">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="81">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="82">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="83">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="84">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="85">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="86">
            <ExpSyntax val="GetParam('xmlErr')&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="87">
            <ExpSyntax val="SetParam('C.sys.LastErrorInfo',GetParam('xmlErr'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <Task>
          <Header Description="NoSource_HyrarchiDestination">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738112" _time="84231" date="18//11//2021" time="23:23:51.8972030"/>
          </Header>
          <ReturnValueExpression/>
          <Resource/>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   JCreate   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="D"/>
                    <WithValue val="1"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <CallTask>
                    <OperationType val="T"/>
                    <TaskID comp="-1" obj="1"/>
                    <Lock val="N"/>
                    <Arguments/>
                    <Wait val="Y"/>
                    <SyncData val="N"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </CallTask>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="C"/>
                    <WithValue val="2"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="JCreate('com.magicsoftware.xpi.json.JsonCreator','(Ljava/lang/String;)V','8')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="JCall(D,'getJsonAsByteArray','()[B')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <Task>
            <Header Description="The root schema">
              <Public/>
              <ExecutionRight/>
              <Resident val="N"/>
              <SQL val="N"/>
              <ReturnValue>
                <ReturnValueAttr/>
                <ParametersAttributes/>
              </ReturnValue>
              <SqlWhereExist val="N"/>
              <TaskType val="B"/>
              <External val="Y"/>
              <LastModified _date="738112" _time="84231" date="18//11//2021" time="23:23:51.8972030"/>
            </Header>
            <ReturnValueExpression/>
            <Resource>
              <Columns>
                <Column id="1" name="D_4_ATTRIBUTE3">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="2" name="D_4_ATTRIBUTE4">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="3" name="D_4_ATTRIBUTE5">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="4" name="D_4_ATTRIBUTE6">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="5" name="D_4_ATTRIBUTE7">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="6" name="D_4_ATTRIBUTE8">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="7" name="D_4_ATTRIBUTE9">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="8" name="D_4_ATTRIBUTE10">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="9" name="D_4_ATTRIBUTE11">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
              </Columns>
            </Resource>
            <Information>
              <Key>
                <Column/>
                <Mode val="N"/>
              </Key>
              <DB/>
              <Sort>
                <CLS val="A"/>
              </Sort>
              <ForceRecordDelete DEL="N"/>
              <EndTaskCondition val="Y"/>
              <EvaluateEndCondition val="A"/>
              <InitialMode val="M"/>
              <Locate Direction="A"/>
              <Range Direction="A"/>
              <VarRange/>
              <TaskProperties>
                <SelectionTable val="N"/>
                <ConfirmUpdate CNFU="N"/>
                <ConfirmCancel val="N"/>
                <ErrorStrategy val="R"/>
                <LockingStrategy val="M"/>
                <CacheStrategy val="T"/>
                <ForceRecordSuffix val="N"/>
                <TransactionMode val="P"/>
                <TransactionBegin val="N"/>
                <PreloadView val="N"/>
                <KeepCreatedContext val="N"/>
              </TaskProperties>
              <SIDE_WIN>
                <AllowOptions val="N"/>
                <AllowQuery val="Y"/>
                <AllowModify val="Y"/>
                <AllowCreate val="Y"/>
                <AllowDelete val="Y"/>
                <AllowLocate val="Y"/>
                <AllowRange val="Y"/>
                <AllowIndexChange val="Y"/>
                <AllowSorting val="Y"/>
                <AllowIOFiles val="Y"/>
                <RecordCycle val="Y"/>
                <AllowEvents val="Y"/>
                <AllowIndexOptimization val="Y"/>
                <AllowLocationInQuery val="Y"/>
                <AllowPrintingData val="N"/>
              </SIDE_WIN>
              <WIN>
                <OpenTaskWindow val="N"/>
                <CloseTaskWindow val="Y"/>
                <ForegroundWindow val="Y"/>
                <FlipFld val="N"/>
                <RefreshTaskWindow ReturnValue="N"/>
              </WIN>
              <BOX>
                <Direction val="V"/>
              </BOX>
            </Information>
            <TaskLogic>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="M"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <_TotalVariabls val="9"/>
                <_TotalVirtuals val="9"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <DATAVIEW_SRC Type="M">
                      <Condition val="N"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </DATAVIEW_SRC>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="H">
                      <ASS/>
                      <Column val="1"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="I">
                      <ASS/>
                      <Column val="2"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="J">
                      <ASS/>
                      <Column val="3"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="K">
                      <ASS/>
                      <Column val="4"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="L">
                      <ASS/>
                      <Column val="5"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="M">
                      <ASS/>
                      <Column val="6"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="N">
                      <ASS/>
                      <Column val="7"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="O">
                      <ASS/>
                      <Column val="8"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="P">
                      <ASS/>
                      <Column val="9"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=" **** Schema  Destination ****"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="1"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="H"/>
                      <WithValue val="2"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="3"/>
                      <ReturnValue/>
                      <Condition Exp="4"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="I"/>
                      <WithValue val="5"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="6"/>
                      <ReturnValue/>
                      <Condition Exp="7"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="J"/>
                      <WithValue val="8"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="9"/>
                      <ReturnValue/>
                      <Condition Exp="10"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="K"/>
                      <WithValue val="11"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="12"/>
                      <ReturnValue/>
                      <Condition Exp="13"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="L"/>
                      <WithValue val="14"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="15"/>
                      <ReturnValue/>
                      <Condition Exp="16"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="M"/>
                      <WithValue val="17"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="18"/>
                      <ReturnValue/>
                      <Condition Exp="19"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="N"/>
                      <WithValue val="20"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="21"/>
                      <ReturnValue/>
                      <Condition Exp="22"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="O"/>
                      <WithValue val="23"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="24"/>
                      <ReturnValue/>
                      <Condition Exp="25"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="P"/>
                      <WithValue val="26"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="27"/>
                      <ReturnValue/>
                      <Condition Exp="28"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
            </TaskLogic>
            <TaskForms>
              <FormEntry _last_test_id="1">
                <PropertyList model="FORM_GUI0">
                  <Width/>
                  <Height/>
                  <_Comment/>
                  <FormName valUnicode="Empty Program"/>
                </PropertyList>
              </FormEntry>
            </TaskForms>
            <Expressions>
              <Expression val="1">
                <ExpSyntax val="JCall(D,'updateJsonData','(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V','C','The root schema','O','','')"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="2">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/object/DFFAttributes/ATTRIBUTE3')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="3">
                <ExpSyntax val="JCall(D,'updateJsonData','(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V','S','The root schema/ATTRIBUTE3','O/S','A',rtrim(H))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="4">
                <ExpSyntax val="rtrim(H) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="5">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/object/DFFAttributes/ATTRIBUTE4')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="6">
                <ExpSyntax val="JCall(D,'updateJsonData','(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V','S','The root schema/ATTRIBUTE4','O/S','A',rtrim(I))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="7">
                <ExpSyntax val="rtrim(I) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="8">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/object/DFFAttributes/ATTRIBUTE5')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="9">
                <ExpSyntax val="JCall(D,'updateJsonData','(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V','S','The root schema/ATTRIBUTE5','O/S','A',rtrim(J))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="10">
                <ExpSyntax val="rtrim(J) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="11">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/object/DFFAttributes/ATTRIBUTE6')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="12">
                <ExpSyntax val="JCall(D,'updateJsonData','(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V','S','The root schema/ATTRIBUTE6','O/S','A',rtrim(K))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="13">
                <ExpSyntax val="rtrim(K) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="14">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/object/DFFAttributes/ATTRIBUTE7')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="15">
                <ExpSyntax val="JCall(D,'updateJsonData','(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V','S','The root schema/ATTRIBUTE7','O/S','A',rtrim(L))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="16">
                <ExpSyntax val="rtrim(L) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="17">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/object/DFFAttributes/ATTRIBUTE8')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="18">
                <ExpSyntax val="JCall(D,'updateJsonData','(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V','S','The root schema/ATTRIBUTE8','O/S','A',rtrim(M))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="19">
                <ExpSyntax val="rtrim(M) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="20">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/object/DFFAttributes/ATTRIBUTE9')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="21">
                <ExpSyntax val="JCall(D,'updateJsonData','(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V','S','The root schema/ATTRIBUTE9','O/S','A',rtrim(N))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="22">
                <ExpSyntax val="rtrim(N) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="23">
                <ExpSyntax val="rTrim( 'zyx' )"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="24">
                <ExpSyntax val="JCall(D,'updateJsonData','(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V','S','The root schema/ATTRIBUTE10','O/S','A',rtrim(O))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="25">
                <ExpSyntax val="rtrim(O) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="26">
                <ExpSyntax val="rTrim( 'zyx' )"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="27">
                <ExpSyntax val="JCall(D,'updateJsonData','(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V','S','The root schema/ATTRIBUTE11','O/S','A',rtrim(P))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="28">
                <ExpSyntax val="rtrim(P) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
            </Expressions>
          </Task>
        </Task>
        <Task>
          <Header Description="NoSource_HyrarchiDestination">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738112" _time="84231" date="18//11//2021" time="23:23:51.8972030"/>
          </Header>
          <ReturnValueExpression/>
          <Resource/>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="F"/>
                    <WithValue val="1"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="5"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="6"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="7"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="8"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="9"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="10"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="G"/>
                    <WithValue val="11"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <CallTask>
                    <OperationType val="T"/>
                    <TaskID comp="-1" obj="1"/>
                    <Lock val="N"/>
                    <Arguments/>
                    <Wait val="Y"/>
                    <SyncData val="N"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </CallTask>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="E"/>
                    <WithValue val="14"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="15"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="UDF ('ibiowritter.openio',Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')),'wb', IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','16',IF(Trim(SharedValGet ('IBProjectEncoding'))='UTF-8','8','A')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="UDF ('ibiowritter.writeLnAsIs'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'&lt;?xml version=&quot;1.0&quot; encoding=&quot;'&amp;Trim(SharedValGet('IBProjectEncoding'))&amp;'&quot; standalone=&quot;no&quot; ?&gt;',F)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'soapenv','http://schemas.xmlsoap.org/soap/envelope/',F)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'xs','http://www.w3.org/2001/XMLSchema',F)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'app1','http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/',F)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'ns1','http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/',F)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'app2','http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/',F)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'ns2','http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/',F)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'msdata','urn:schemas-microsoft-com:xml-msdata',F)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'xsi','http://www.w3.org/2001/XMLSchema-instance',F)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',IF(Trim(SharedValGet ('IBProjectEncoding'))='UTF-8','_8',''))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(G),'L','','','',F,0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="UDF ('ibiowritter.closeio',F)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="File2Blb(Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="FileDelete(Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <Task>
            <Header Description="soapenv:Envelope">
              <Public/>
              <ExecutionRight/>
              <Resident val="N"/>
              <SQL val="N"/>
              <ReturnValue>
                <ReturnValueAttr/>
                <ParametersAttributes/>
              </ReturnValue>
              <SqlWhereExist val="N"/>
              <TaskType val="B"/>
              <External val="Y"/>
              <LastModified _date="738112" _time="84231" date="18//11//2021" time="23:23:51.8972030"/>
            </Header>
            <ReturnValueExpression/>
            <Resource>
              <Columns>
                <Column id="1" name="D_2_operationMode">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="2" name="D_2_EntityName">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="3" name="D_2_ContextValue">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="4" name="D_2_UserKeyA">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="5" name="D_2_DFFAttributes">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
              </Columns>
            </Resource>
            <Information>
              <Key>
                <Column/>
                <Mode val="N"/>
              </Key>
              <DB/>
              <Sort>
                <CLS val="A"/>
              </Sort>
              <ForceRecordDelete DEL="N"/>
              <EndTaskCondition val="Y"/>
              <EvaluateEndCondition val="A"/>
              <InitialMode val="M"/>
              <Locate Direction="A"/>
              <Range Direction="A"/>
              <VarRange/>
              <TaskProperties>
                <SelectionTable val="N"/>
                <ConfirmUpdate CNFU="N"/>
                <ConfirmCancel val="N"/>
                <ErrorStrategy val="R"/>
                <LockingStrategy val="M"/>
                <CacheStrategy val="T"/>
                <ForceRecordSuffix val="N"/>
                <TransactionMode val="P"/>
                <TransactionBegin val="N"/>
                <PreloadView val="N"/>
                <KeepCreatedContext val="N"/>
              </TaskProperties>
              <SIDE_WIN>
                <AllowOptions val="N"/>
                <AllowQuery val="Y"/>
                <AllowModify val="Y"/>
                <AllowCreate val="Y"/>
                <AllowDelete val="Y"/>
                <AllowLocate val="Y"/>
                <AllowRange val="Y"/>
                <AllowIndexChange val="Y"/>
                <AllowSorting val="Y"/>
                <AllowIOFiles val="Y"/>
                <RecordCycle val="Y"/>
                <AllowEvents val="Y"/>
                <AllowIndexOptimization val="Y"/>
                <AllowLocationInQuery val="Y"/>
                <AllowPrintingData val="N"/>
              </SIDE_WIN>
              <WIN>
                <OpenTaskWindow val="N"/>
                <CloseTaskWindow val="Y"/>
                <ForegroundWindow val="Y"/>
                <FlipFld val="N"/>
                <RefreshTaskWindow ReturnValue="N"/>
              </WIN>
              <BOX>
                <Direction val="V"/>
              </BOX>
            </Information>
            <TaskLogic>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="M"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <_TotalVariabls val="5"/>
                <_TotalVirtuals val="5"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <DATAVIEW_SRC Type="M">
                      <Condition val="N"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </DATAVIEW_SRC>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="H">
                      <ASS/>
                      <Column val="1"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="I">
                      <ASS/>
                      <Column val="2"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="J">
                      <ASS/>
                      <Column val="3"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="K">
                      <ASS/>
                      <Column val="4"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="L">
                      <ASS/>
                      <Column val="5"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=" **** Schema  Destination ****"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="1"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="H"/>
                      <WithValue val="2"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="3"/>
                      <ReturnValue/>
                      <Condition Exp="4"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="I"/>
                      <WithValue val="5"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="6"/>
                      <ReturnValue/>
                      <Condition Exp="7"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="J"/>
                      <WithValue val="8"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="9"/>
                      <ReturnValue/>
                      <Condition Exp="10"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="K"/>
                      <WithValue val="11"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="12"/>
                      <ReturnValue/>
                      <Condition Exp="13"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="L"/>
                      <WithValue val="14"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="15"/>
                      <ReturnValue/>
                      <Condition Exp="16"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
            </TaskLogic>
            <TaskForms>
              <FormEntry _last_test_id="1">
                <PropertyList model="FORM_GUI0">
                  <Width/>
                  <Height/>
                  <_Comment/>
                  <FormName valUnicode="Empty Program"/>
                </PropertyList>
              </FormEntry>
            </TaskForms>
            <Expressions>
              <Expression val="1">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(G),'C','soapenv:Envelope','soapenv:Envelope','',F,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="2">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/operationMode')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="3">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(G),'S','app2:operationMode','soapenv:Envelope/soapenv:Body/app2:updateDffEntityDetails/app2:operationMode',rtrim(H),F,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="4">
                <ExpSyntax val="rtrim(H) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="5">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/object/EntityName')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="6">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(G),'S','app1:EntityName','soapenv:Envelope/soapenv:Body/app2:updateDffEntityDetails/app2:object/app1:EntityName',rtrim(I),F,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="7">
                <ExpSyntax val="rtrim(I) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="8">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/object/ContextValue')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="9">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(G),'S','app1:ContextValue','soapenv:Envelope/soapenv:Body/app2:updateDffEntityDetails/app2:object/app1:ContextValue',rtrim(J),F,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="10">
                <ExpSyntax val="rtrim(J) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="11">
                <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/object/UserKeyA')"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="12">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(G),'S','app1:UserKeyA','soapenv:Envelope/soapenv:Body/app2:updateDffEntityDetails/app2:object/app1:UserKeyA',rtrim(K),F,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="13">
                <ExpSyntax val="rtrim(K) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="14">
                <ExpSyntax val="rTrim( BlobRemoveBOM (GetParam ('000000000002000000000033F.InputjsonPart')) )"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="15">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(G),'S','app1:DFFAttributes','soapenv:Envelope/soapenv:Body/app2:updateDffEntityDetails/app2:object/app1:DFFAttributes',rtrim(L),F,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="16">
                <ExpSyntax val="rtrim(L) &lt;&gt; ''"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
            </Expressions>
          </Task>
        </Task>
        <Task>
          <Header Description="Variable_3">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738112" _time="84231" date="18//11//2021" time="23:23:51.8982027"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <Columns>
              <Column id="1" name="D_3_C.ObjectType">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="510"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="255"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="2" name="D_3_C.Operation">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="510"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="255"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="3" name="D_3_C.RequestId">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_NUMERIC"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="6"/>
                  <Size val="8"/>
                  <_Dec val="0"/>
                  <_Whole val="15"/>
                  <_Negative val="1"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="N15"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
            </Columns>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="3"/>
              <_TotalVirtuals val="3"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="H">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="I">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="J">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=" **** Schema  Destination ****"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="H"/>
                    <WithValue val="1"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="I"/>
                    <WithValue val="3"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="J"/>
                    <WithValue val="5"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="6"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Type')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="SetParam('C.ObjectType',IF(rTrim( H )&lt;&gt;'',rTrim( H ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Operation')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam('C.Operation',IF(rTrim( I )&lt;&gt;'',rTrim( I ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="Val(JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/RequestId'),'N9')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="SetParam('C.RequestId',J)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
