<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models>
      <Object name="Text_1000">
        <PropertyList model="FIELD">
          <Model attr_obj="FIELD_UNICODE"/>
          <_FieldStyle/>
          <Picture valUnicode="1000"/>
          <Size val="1000"/>
        </PropertyList>
      </Object>
    </Models>
  </ModelsRepository>
  <DataSourceRepository/>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="map_2_4_8">
          <Public val="map_2_4_8"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="738112" _time="84235" date="18//11//2021" time="23:23:55.1092659"/>
        </Header>
        <ReturnValueExpression/>
        <Resource>
          <Columns>
            <Column id="1" name="1_Source_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="2" name="1_Source_JSonJCreateSourceBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="3" name="1_Source_JsonValidateError">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_ALPHA"/>
                <StoredAs/>
                <Size val="32000"/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="32000"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="4" name="2_Destination_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="5" name="2_Destination_XMLValidate">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_LOGICAL"/>
                <StoredAs/>
                <Size/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="5"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="6" name="2_Destination_XMLVectorValidate">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <CellModel attr_obj="FIELD_BLOB" comp="-1" obj="1"/>
                <StoredAs val="29"/>
                <Size/>
                <_FieldStyle val="4"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="7" name="2_Destination_XMLIoPtrDll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole val="3"/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="8" name="2_Destination_XMLEncoding_w_Dll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_ALPHA"/>
                <StoredAs val="2"/>
                <Size val="3"/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
          </Columns>
        </Resource>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <_TotalVariabls val="8"/>
            <_TotalVirtuals val="8"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Select Name="A">
                  <ASS/>
                  <Column val="1"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="B">
                  <ASS/>
                  <Column val="2"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="C">
                  <ASS/>
                  <Column val="3"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="D">
                  <ASS/>
                  <Column val="4"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="E">
                  <ASS/>
                  <Column val="5"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="F">
                  <ASS/>
                  <Column val="6"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="G">
                  <ASS/>
                  <Column val="7"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="H">
                  <ASS/>
                  <Column val="8"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="1"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="2"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="Begin Json Validation Error"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="C"/>
                  <WithValue val="3"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="4"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="5"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="6"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="7"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="8"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="9"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="10"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="11"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="12"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="After Json Validation Error"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="13"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   JCreate   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="B"/>
                  <WithValue val="14"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   Begin ErrorMsg   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="15"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="17"/>
                  <ReturnValue/>
                  <Condition Exp="16"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="18"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="19"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="20"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="21"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="22"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="23"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="24"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="25"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   End ErrorMsg   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="27"/>
                  <ReturnValue/>
                  <Condition Exp="26"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="28"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="29"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="31"/>
                  <ReturnValue/>
                  <Condition Exp="30"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="32"/>
                  <ReturnValue/>
                  <Condition Exp="30"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="33"/>
                  <ReturnValue/>
                  <Condition Exp="30"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="34"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="35"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="36"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="37"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="30"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="38"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="Begin XSD Validation Error"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="E"/>
                  <WithValue val="39"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="40"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="41"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="42"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="43"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="44"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="45"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="46"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="47"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="F"/>
                  <WithValue val="48"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="L">
                  <Condition Exp="49"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="50"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="After XSD Validation Error"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="51"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-2********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="52"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="Begin Json Validation Error"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="C"/>
                  <WithValue val="53"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="54"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="55"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="56"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="57"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="58"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="59"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="60"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="61"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="62"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="After Json Validation Error"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="63"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   JCreate   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="B"/>
                  <WithValue val="64"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   Begin ErrorMsg   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="65"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="67"/>
                  <ReturnValue/>
                  <Condition Exp="66"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="68"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="69"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="70"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="71"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="72"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="73"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="74"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="75"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="***   End ErrorMsg   ***"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="77"/>
                  <ReturnValue/>
                  <Condition Exp="76"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="78"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="2"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="79"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="81"/>
                  <ReturnValue/>
                  <Condition Exp="80"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="82"/>
                  <ReturnValue/>
                  <Condition Exp="80"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="83"/>
                  <ReturnValue/>
                  <Condition Exp="80"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="84"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="85"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="86"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="87"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="80"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="88"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-2********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="90"/>
                  <ReturnValue/>
                  <Condition Exp="89"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="SetParam('xmlErr',' ')"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="GetParam ('C.HTTP_Body')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="JCallStatic('com.magicsoftware.xpi.json.Utils.validateJsonInstance','(Ljava/lang/String;[B)Ljava/lang/String;',TranslateNR(getFullPath(Trim('Files\NS_FU\NetSuite\CreateLocationSchema.json'))),A)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="Trim(C)&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="SetParam('Error',462)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans (Trim(C)))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="SetParam('xmlErr','FUSION BUSINESS PROCESS,Location,Create Location  Mapping,JSON_1,'&amp;Trim(C)&amp;ASCIIChr(13)&amp;ASCIIChr(10))"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="BlobSize(A)&gt;0 AND (GetParam('xpi_SourceJsonIsNotWellFormed') = NULL() or GetParam('xpi_SourceJsonIsNotWellFormed') &gt; 0 ) "/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="JCreate('com.magicsoftware.xpi.json.JsonParser','([BZ)V',A,SharedValGet('IB_NullifJSONSourceNonExistentTagValue'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',JCall(B,'getElementsCount','(Ljava/lang/String;Z)Ljava/lang/Integer;','Root','TRUE'LOG))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="JExceptionOccurred() "/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',0)"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="18">
            <ExpSyntax val="GetParam('xpi_SourceJsonIsNotWellFormed') = 0"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="19">
            <ExpSyntax val="SetParam('Error',465)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="20">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source Json is not well-formed.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="21">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="22">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="23">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="24">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="25">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="26">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="27">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="28">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="29">
            <ExpSyntax val="BlobSize(A)&gt;0 AND Trim(C) = '' AND JExceptionOccurred()='FALSE'LOG AND GetParam('xpi_SourceJsonIsNotWellFormed') &gt; 0 "/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="30">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="31">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="32">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="33">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="34">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="35">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="36">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="37">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="38">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="39">
            <ExpSyntax val="xmlvalidate(D,'http://schemas.xmlsoap.org/soap/envelope/ '&amp;repstr(TranslateNR(getFullPath('Files\NS_FU\Fusion\Location\Create\Request\Location.xsd')),' ','%20'))"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="40">
            <ExpSyntax val="NOT(E)"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="41">
            <ExpSyntax val="SetParam('Error',453)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="42">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans (VecGet (XMLValidationError(), 1)))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="43">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="44">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="45">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="46">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="47">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="48">
            <ExpSyntax val="xmlValidationError ()"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="49">
            <ExpSyntax val="loopcounter()&lt;=vecsize(F)"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="50">
            <ExpSyntax val="SetParam('xmlErr',GetParam('xmlErr')&amp;'FUSION BUSINESS PROCESS,Location,Create Location  Mapping,XML_2,'&amp;VecGet(F,LoopCounter())&amp;ASCIIChr(13)&amp;ASCIIChr(10))"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="51">
            <ExpSyntax val="SetParam ('C.RequestXML',D)"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="52">
            <ExpSyntax val="GetParam ('C.HTTP_Body')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="53">
            <ExpSyntax val="JCallStatic('com.magicsoftware.xpi.json.Utils.validateJsonInstance','(Ljava/lang/String;[B)Ljava/lang/String;',TranslateNR(getFullPath(Trim('Files\NS_FU\NetSuite\CreateLocationSchema.json'))),A)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="54">
            <ExpSyntax val="Trim(C)&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="55">
            <ExpSyntax val="SetParam('Error',462)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="56">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans (Trim(C)))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="57">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="58">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="59">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="60">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="61">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="62">
            <ExpSyntax val="SetParam('xmlErr','FUSION BUSINESS PROCESS,Location,Create Location  Mapping,JSON_1,'&amp;Trim(C)&amp;ASCIIChr(13)&amp;ASCIIChr(10))"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="63">
            <ExpSyntax val="BlobSize(A)&gt;0 AND (GetParam('xpi_SourceJsonIsNotWellFormed') = NULL() or GetParam('xpi_SourceJsonIsNotWellFormed') &gt; 0 ) "/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="64">
            <ExpSyntax val="JCreate('com.magicsoftware.xpi.json.JsonParser','([BZ)V',A,SharedValGet('IB_NullifJSONSourceNonExistentTagValue'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="65">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',JCall(B,'getElementsCount','(Ljava/lang/String;Z)Ljava/lang/Integer;','Root','TRUE'LOG))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="66">
            <ExpSyntax val="JExceptionOccurred() "/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="67">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',0)"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="68">
            <ExpSyntax val="GetParam('xpi_SourceJsonIsNotWellFormed') = 0"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="69">
            <ExpSyntax val="SetParam('Error',465)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="70">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source Json is not well-formed.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="71">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="72">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="73">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="74">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="75">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="76">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="77">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="78">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="79">
            <ExpSyntax val="BlobSize(A)&gt;0 AND Trim(C) = '' AND JExceptionOccurred()='FALSE'LOG AND GetParam('xpi_SourceJsonIsNotWellFormed') &gt; 0 "/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="80">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="81">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="82">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="83">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="84">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="85">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="86">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="87">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="88">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="89">
            <ExpSyntax val="GetParam('xmlErr')&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="90">
            <ExpSyntax val="SetParam('C.sys.LastErrorInfo',GetParam('xmlErr'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <Task>
          <Header Description="NoSource_HyrarchiDestination">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738112" _time="84235" date="18//11//2021" time="23:23:55.1092659"/>
          </Header>
          <ReturnValueExpression/>
          <Resource/>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="G"/>
                    <WithValue val="1"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="5"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="6"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="7"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="8"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="9"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="10"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="H"/>
                    <WithValue val="11"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <CallTask>
                    <OperationType val="T"/>
                    <TaskID comp="-1" obj="1"/>
                    <Lock val="N"/>
                    <Arguments/>
                    <Wait val="Y"/>
                    <SyncData val="N"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </CallTask>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="D"/>
                    <WithValue val="14"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="15"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="UDF ('ibiowritter.openio',Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')),'wb', IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','16',IF(Trim(SharedValGet ('IBProjectEncoding'))='UTF-8','8','A')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="UDF ('ibiowritter.writeLnAsIs'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'&lt;?xml version=&quot;1.0&quot; encoding=&quot;'&amp;Trim(SharedValGet('IBProjectEncoding'))&amp;'&quot; standalone=&quot;no&quot; ?&gt;',G)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'soapenv','http://schemas.xmlsoap.org/soap/envelope/',G)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'xs','http://www.w3.org/2001/XMLSchema',G)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'ns2','http://xmlns.oracle.com/apps/cdm/foundation/parties/locationService/',G)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'app1','http://xmlns.oracle.com/apps/cdm/foundation/parties/locationService/',G)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'app2','http://xmlns.oracle.com/apps/cdm/foundation/parties/locationService/applicationModule/types/',G)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'ns1','http://xmlns.oracle.com/apps/cdm/foundation/parties/locationService/applicationModule/types/',G)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'msdata','urn:schemas-microsoft-com:xml-msdata',G)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'xsi','http://www.w3.org/2001/XMLSchema-instance',G)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',IF(Trim(SharedValGet ('IBProjectEncoding'))='UTF-8','_8',''))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'L','','','',G,0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="UDF ('ibiowritter.closeio',G)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="File2Blb(Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="FileDelete(Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <Task>
            <Header Description="NoSource_GeneralDestination">
              <Public/>
              <ExecutionRight/>
              <Resident val="N"/>
              <SQL val="N"/>
              <ReturnValue>
                <ReturnValueAttr/>
                <ParametersAttributes/>
              </ReturnValue>
              <SqlWhereExist val="N"/>
              <TaskType val="B"/>
              <External val="Y"/>
              <LastModified _date="738112" _time="84235" date="18//11//2021" time="23:23:55.1092659"/>
            </Header>
            <ReturnValueExpression/>
            <Resource/>
            <Information>
              <Key>
                <Column/>
                <Mode val="N"/>
              </Key>
              <DB/>
              <Sort>
                <CLS val="A"/>
              </Sort>
              <ForceRecordDelete DEL="N"/>
              <EndTaskCondition val="Y"/>
              <EvaluateEndCondition val="A"/>
              <InitialMode val="M"/>
              <Locate Direction="A"/>
              <Range Direction="A"/>
              <VarRange/>
              <TaskProperties>
                <SelectionTable val="N"/>
                <ConfirmUpdate CNFU="N"/>
                <ConfirmCancel val="N"/>
                <ErrorStrategy val="R"/>
                <LockingStrategy val="M"/>
                <CacheStrategy val="T"/>
                <ForceRecordSuffix val="N"/>
                <TransactionMode val="P"/>
                <TransactionBegin val="N"/>
                <PreloadView val="N"/>
                <KeepCreatedContext val="N"/>
              </TaskProperties>
              <SIDE_WIN>
                <AllowOptions val="N"/>
                <AllowQuery val="Y"/>
                <AllowModify val="Y"/>
                <AllowCreate val="Y"/>
                <AllowDelete val="Y"/>
                <AllowLocate val="Y"/>
                <AllowRange val="Y"/>
                <AllowIndexChange val="Y"/>
                <AllowSorting val="Y"/>
                <AllowIOFiles val="Y"/>
                <RecordCycle val="Y"/>
                <AllowEvents val="Y"/>
                <AllowIndexOptimization val="Y"/>
                <AllowLocationInQuery val="Y"/>
                <AllowPrintingData val="N"/>
              </SIDE_WIN>
              <WIN>
                <OpenTaskWindow val="N"/>
                <CloseTaskWindow val="Y"/>
                <ForegroundWindow val="Y"/>
                <FlipFld val="N"/>
                <RefreshTaskWindow ReturnValue="N"/>
              </WIN>
              <BOX>
                <Direction val="V"/>
              </BOX>
            </Information>
            <TaskLogic>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="M"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <DATAVIEW_SRC Type="M">
                      <Condition val="N"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </DATAVIEW_SRC>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=" **** Schema  Destination ****"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <CallTask>
                      <OperationType val="T"/>
                      <TaskID comp="-1" obj="1"/>
                      <Lock val="N"/>
                      <Arguments/>
                      <Wait val="Y"/>
                      <SyncData val="N"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </CallTask>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
            </TaskLogic>
            <TaskForms>
              <FormEntry _last_test_id="1">
                <PropertyList model="FORM_GUI0">
                  <Width/>
                  <Height/>
                  <_Comment/>
                  <FormName valUnicode="Empty Program"/>
                </PropertyList>
              </FormEntry>
            </TaskForms>
            <Task>
              <Header Description="soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location">
                <Public/>
                <ExecutionRight/>
                <Resident val="N"/>
                <SQL val="N"/>
                <ReturnValue>
                  <ReturnValueAttr/>
                  <ParametersAttributes/>
                </ReturnValue>
                <SqlWhereExist val="N"/>
                <TaskType val="B"/>
                <External val="Y"/>
                <LastModified _date="738112" _time="84235" date="18//11//2021" time="23:23:55.1092659"/>
              </Header>
              <ReturnValueExpression/>
              <Resource>
                <Columns>
                  <Column id="1" name="D_2_RequestId">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="2" name="D_2_AddressEffectiveDate">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="3" name="D_2_EffectiveDate">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="4" name="D_2_Country">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="5" name="D_2_Address1">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="6" name="D_2_City">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="7" name="D_2_PostalCode">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="8" name="D_2_State">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="9" name="D_2_CreatedByModule">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                </Columns>
              </Resource>
              <Information>
                <Key>
                  <Column/>
                  <Mode val="N"/>
                </Key>
                <DB/>
                <Sort>
                  <CLS val="A"/>
                </Sort>
                <ForceRecordDelete DEL="N"/>
                <EndTaskCondition val="Y"/>
                <EvaluateEndCondition val="A"/>
                <InitialMode val="M"/>
                <Locate Direction="A"/>
                <Range Direction="A"/>
                <VarRange/>
                <TaskProperties>
                  <SelectionTable val="N"/>
                  <ConfirmUpdate CNFU="N"/>
                  <ConfirmCancel val="N"/>
                  <ErrorStrategy val="R"/>
                  <LockingStrategy val="M"/>
                  <CacheStrategy val="T"/>
                  <ForceRecordSuffix val="N"/>
                  <TransactionMode val="P"/>
                  <TransactionBegin val="N"/>
                  <PreloadView val="N"/>
                  <KeepCreatedContext val="N"/>
                </TaskProperties>
                <SIDE_WIN>
                  <AllowOptions val="N"/>
                  <AllowQuery val="Y"/>
                  <AllowModify val="Y"/>
                  <AllowCreate val="Y"/>
                  <AllowDelete val="Y"/>
                  <AllowLocate val="Y"/>
                  <AllowRange val="Y"/>
                  <AllowIndexChange val="Y"/>
                  <AllowSorting val="Y"/>
                  <AllowIOFiles val="Y"/>
                  <RecordCycle val="Y"/>
                  <AllowEvents val="Y"/>
                  <AllowIndexOptimization val="Y"/>
                  <AllowLocationInQuery val="Y"/>
                  <AllowPrintingData val="N"/>
                </SIDE_WIN>
                <WIN>
                  <OpenTaskWindow val="N"/>
                  <CloseTaskWindow val="Y"/>
                  <ForegroundWindow val="Y"/>
                  <FlipFld val="N"/>
                  <RefreshTaskWindow ReturnValue="N"/>
                </WIN>
                <BOX>
                  <Direction val="V"/>
                </BOX>
              </Information>
              <TaskLogic>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="M"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <_TotalVariabls val="9"/>
                  <_TotalVirtuals val="9"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <DATAVIEW_SRC Type="M">
                        <Condition val="N"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </DATAVIEW_SRC>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="I">
                        <ASS/>
                        <Column val="1"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="J">
                        <ASS/>
                        <Column val="2"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="K">
                        <ASS/>
                        <Column val="3"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="L">
                        <ASS/>
                        <Column val="4"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="M">
                        <ASS/>
                        <Column val="5"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="N">
                        <ASS/>
                        <Column val="6"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="O">
                        <ASS/>
                        <Column val="7"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="P">
                        <ASS/>
                        <Column val="8"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="Q">
                        <ASS/>
                        <Column val="9"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=" **** Schema  Destination ****"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="1"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="I"/>
                        <WithValue val="2"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="3"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="J"/>
                        <WithValue val="4"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="5"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="K"/>
                        <WithValue val="6"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="7"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="L"/>
                        <WithValue val="8"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="9"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="M"/>
                        <WithValue val="10"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="11"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="N"/>
                        <WithValue val="12"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="13"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="O"/>
                        <WithValue val="14"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="15"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="P"/>
                        <WithValue val="16"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="17"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="Q"/>
                        <WithValue val="18"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="19"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                </LogicUnit>
              </TaskLogic>
              <TaskForms>
                <FormEntry _last_test_id="1">
                  <PropertyList model="FORM_GUI0">
                    <Width/>
                    <Height/>
                    <_Comment/>
                    <FormName valUnicode="Empty Program"/>
                  </PropertyList>
                </FormEntry>
              </TaskForms>
              <Expressions>
                <Expression val="1">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'C','app2:location','soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location','',G,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="2">
                  <ExpSyntax val="rTrim( Trim (Str (Val(JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/RequestId'),'N9'),'')) )"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="3">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'S','ns2:RequestId','soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location/ns2:RequestId',rtrim(I),G,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="4">
                  <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/AddressEffectiveDate')"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="5">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'S','ns2:AddressEffectiveDate','soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location/ns2:AddressEffectiveDate',rtrim(J),G,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="6">
                  <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/EffectiveDate')"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="7">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'S','ns2:EffectiveDate','soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location/ns2:EffectiveDate',rtrim(K),G,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="8">
                  <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/Country')"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="9">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'S','ns2:Country','soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location/ns2:Country',rtrim(L),G,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="10">
                  <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/Address1')"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="11">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'S','ns2:Address1','soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location/ns2:Address1',rtrim(M),G,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="12">
                  <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/City')"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="13">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'S','ns2:City','soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location/ns2:City',rtrim(N),G,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="14">
                  <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/PostalCode')"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="15">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'S','ns2:PostalCode','soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location/ns2:PostalCode',rtrim(O),G,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="16">
                  <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/State')"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="17">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'S','ns2:State','soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location/ns2:State',rtrim(P),G,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="18">
                  <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Data/CreatedByModule')"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="19">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(H),'S','ns2:CreatedByModule','soapenv:Envelope/soapenv:Body/app2:createLocation/app2:location/ns2:CreatedByModule',rtrim(Q),G,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
              </Expressions>
            </Task>
          </Task>
        </Task>
        <Task>
          <Header Description="Variable_3">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738112" _time="84235" date="18//11//2021" time="23:23:55.1092659"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <Columns>
              <Column id="1" name="D_3_C.ObjectType">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="510"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="255"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="2" name="D_3_C.Operation">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="510"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="255"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="3" name="D_3_C.RequestId">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_NUMERIC"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="6"/>
                  <Size val="8"/>
                  <_Dec val="0"/>
                  <_Whole val="15"/>
                  <_Negative val="1"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="N15"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
            </Columns>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="3"/>
              <_TotalVirtuals val="3"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="I">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="J">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="K">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=" **** Schema  Destination ****"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="I"/>
                    <WithValue val="1"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="J"/>
                    <WithValue val="3"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="K"/>
                    <WithValue val="5"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="6"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Type')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="SetParam('C.ObjectType',IF(rTrim( I )&lt;&gt;'',rTrim( I ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/Operation')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam('C.Operation',IF(rTrim( J )&lt;&gt;'',rTrim( J ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="Val(JCall(B,'getValueByXPath','(Ljava/lang/String;)Ljava/lang/String;','The root schema/RequestId'),'N9')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="SetParam('C.RequestId',K)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
