<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models/>
  </ModelsRepository>
  <DataSourceRepository/>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="map_2_7_12">
          <Public val="map_2_7_12"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="738112" _time="84237" date="18//11//2021" time="23:23:57.0833037"/>
        </Header>
        <ReturnValueExpression/>
        <Resource>
          <Columns>
            <Column id="1" name="1_Source_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
          </Columns>
        </Resource>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <_TotalVariabls val="1"/>
            <_TotalVirtuals val="1"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Select Name="A">
                  <ASS/>
                  <Column val="1"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="1"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="2"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="4"/>
                  <ReturnValue/>
                  <Condition Exp="3"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="5"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="6"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="8"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="9"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="10"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="11"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="12"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="13"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="14"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="7"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="15"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-2********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="16"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="18"/>
                  <ReturnValue/>
                  <Condition Exp="17"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="19"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="2"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="20"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="22"/>
                  <ReturnValue/>
                  <Condition Exp="21"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition Exp="21"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="24"/>
                  <ReturnValue/>
                  <Condition Exp="21"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="25"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="26"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="27"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="28"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="21"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="29"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-2********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="31"/>
                  <ReturnValue/>
                  <Condition Exp="30"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="SetParam('xmlErr',' ')"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="GetParam ('C.FusionResponse')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="BlobSize(A)&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="GetParam ('C.FusionResponse')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="18">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="19">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="20">
            <ExpSyntax val="BlobSize(A)&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="21">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="22">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="23">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="24">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="25">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="26">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="27">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="28">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="29">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="30">
            <ExpSyntax val="GetParam('xmlErr')&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="31">
            <ExpSyntax val="SetParam('C.sys.LastErrorInfo',GetParam('xmlErr'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <Task>
          <Header Description="Variable_2">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738112" _time="84237" date="18//11//2021" time="23:23:57.0843013"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO Column="A">
              <Description val="xmlSource"/>
              <Format/>
              <Media val="V"/>
              <Access val="R"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
            <Columns>
              <Column id="1" name="D_2_C.FusionLocationID">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="200"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="100"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="2" name="D_2_C.FusionResponseStatus">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="3" name="D_2_C.MessageID">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="200"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="100"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
            </Columns>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y" Exp="60"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="3"/>
              <_TotalVirtuals val="3"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="B">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="C">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="D">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Block SetParam RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="29"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="30"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="31"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="32"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="33"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="34"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="35"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="36"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Block SetParam RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="38"/>
                    <ReturnValue/>
                    <Condition Exp="37"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="40"/>
                    <ReturnValue/>
                    <Condition Exp="39"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="41"/>
                    <ReturnValue/>
                    <Condition Exp="39"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="43"/>
                    <ReturnValue/>
                    <Condition Exp="42"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="44"/>
                    <ReturnValue/>
                    <Condition Exp="42"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="46"/>
                    <ReturnValue/>
                    <Condition Exp="45"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="47"/>
                    <ReturnValue/>
                    <Condition Exp="45"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="48"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End SetParam XmlCnt RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="49"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="50"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="L">
                    <Condition Exp="51"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="52"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="53"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="55"/>
                    <ReturnValue/>
                    <Condition Exp="54"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="61"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=" **** Schema  Destination ****"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="B"/>
                    <WithValue val="62"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="63"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="C"/>
                    <WithValue val="64"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="65"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="D"/>
                    <WithValue val="66"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="67"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="1"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <RaiseEvent>
                    <Event>
                      <EventType val="P"/>
                      <Exp val="5"/>
                      <PublicObject/>
                    </Event>
                    <Wait val="89"/>
                    <Arguments>
                      <Argument>
                        <id val="0"/>
                        <Expression val="6"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="7"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Skip val="Y"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="8"/>
                        <Skip val="N"/>
                      </Argument>
                    </Arguments>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </RaiseEvent>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Temp SetParam TP   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="9"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="10"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="11"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="14"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="15"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="16"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="19"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="20"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="21"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="24"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="25"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="26"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Temp SetParam TP   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Temp SetParam TS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="17"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="18"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="22"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="23"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="27"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="28"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Temp SetParam TS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="XMLCnt(0,1,'/Envelope')=0"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="SetParam('Error',455)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source XML is not well-formed.'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="'SaveInternalMSG'"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="15"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="'txt'"/>
              <ExpAttribute val="T"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="SetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',GetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',GetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="SetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="16">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="17">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse',GetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="18">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse',GetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="19">
              <ExpSyntax val="SetParam('Temp_1_S_2_7_12_1_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_7_12_1_Envelope/Body'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="20">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_7_12_1_Envelope/Body'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="21">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="22">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body',GetParam('Temp_1_S_2_7_12_1_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="23">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body',GetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="24">
              <ExpSyntax val="SetParam('Temp_1_S_2_7_12_1_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_7_12_1_Envelope'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="25">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_7_12_1_Envelope'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="26">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="27">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope',GetParam('Temp_1_S_2_7_12_1_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="28">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope',GetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="29">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="30">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="31">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="32">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="33">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="34">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="35">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="36">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="37">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="38">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope',XMLCnt(0,1,'/Envelope'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="39">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="40">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope',GetParam('S_2_7_12_1_Envelope')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="41">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body',XMLCnt(0,1,'/Envelope['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope'),''))&amp;']/Body'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="42">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="43">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body',GetParam('S_2_7_12_1_Envelope/Body')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="44">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse',XMLCnt(0,1,'/Envelope['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope'),''))&amp;']/Body['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body'),''))&amp;']/createOrganizationResponse'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="45">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="46">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse',GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="47">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',XMLCnt(0,1,'/Envelope['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope'),''))&amp;']/Body['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body'),''))&amp;']/createOrganizationResponse['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse'),''))&amp;']/result'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="48">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="49">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartyUsageAssignment',1)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="50">
              <ExpSyntax val="SetParam('Loopcnt_1',1)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="51">
              <ExpSyntax val="LoopCounter() &lt;= XMLCnt(0,1,'/Envelope[1]/Body[1]/createOrganizationResponse[1]/result['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'),''))&amp;']/Value[1]/PartyUsageAssignment') AND Not('TRUE'LOG)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="52">
              <ExpSyntax val="SetParam('Loopcnt_1',LoopCounter()+1)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="53">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartyUsageAssignment',LoopCounter()+1)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="54">
              <ExpSyntax val="Not('TRUE'LOG)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="55">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartyUsageAssignment',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="56">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="57">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="58">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="59">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="60">
              <ExpSyntax val="(ExpCalc('56'EXP)  AND ExpCalc('57'EXP)  AND ExpCalc('58'EXP)  AND ExpCalc('59'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="61">
              <ExpSyntax val="GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')&gt;0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="62">
              <ExpSyntax val="xmlget(0,1,'/Envelope['&amp;trim(str(getparam('S_2_7_12_1_Envelope'),''))&amp;']'&amp;'/Body['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body'),''))&amp;']'&amp;'/createOrganizationResponse['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body/createOrganizationResponse'),''))&amp;']'&amp;'/result['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'),''))&amp;']'&amp;'/Value['&amp;'1'&amp;']'&amp;'/PartyId','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="63">
              <ExpSyntax val="SetParam('C.FusionLocationID',IF(rTrim( B )&lt;&gt;'',rTrim( B ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="64">
              <ExpSyntax val="xmlget(0,1,'/Envelope['&amp;trim(str(getparam('S_2_7_12_1_Envelope'),''))&amp;']'&amp;'/Body['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body'),''))&amp;']'&amp;'/createOrganizationResponse['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body/createOrganizationResponse'),''))&amp;']'&amp;'/result['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'),''))&amp;']'&amp;'/Value['&amp;'1'&amp;']'&amp;'/PartyUsageAssignment['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartyUsageAssignment'),''))&amp;']'&amp;'/StatusFlag','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="65">
              <ExpSyntax val="SetParam('C.FusionResponseStatus',IF(rTrim( C )&lt;&gt;'',rTrim( C ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="66">
              <ExpSyntax val="xmlget(0,1,'/Envelope['&amp;trim(str(getparam('S_2_7_12_1_Envelope'),''))&amp;']'&amp;'/Header['&amp;'1'&amp;']'&amp;'/MessageID','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="67">
              <ExpSyntax val="SetParam('C.MessageID',IF(rTrim( D )&lt;&gt;'',rTrim( D ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
        <Task>
          <Header Description="Variable_3">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738112" _time="84237" date="18//11//2021" time="23:23:57.0863010"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO Column="A">
              <Description val="xmlSource"/>
              <Format/>
              <Media val="V"/>
              <Access val="R"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
            <Columns>
              <Column id="1" name="D_3_C.PartySiteId">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="1000"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="500"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
            </Columns>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y" Exp="82"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="1"/>
              <_TotalVirtuals val="1"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="B">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Block SetParam RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="39"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="40"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="41"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="42"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="43"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="44"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="45"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="46"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="47"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="48"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="49"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="50"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Block SetParam RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="52"/>
                    <ReturnValue/>
                    <Condition Exp="51"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="54"/>
                    <ReturnValue/>
                    <Condition Exp="53"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="55"/>
                    <ReturnValue/>
                    <Condition Exp="53"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="57"/>
                    <ReturnValue/>
                    <Condition Exp="56"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="58"/>
                    <ReturnValue/>
                    <Condition Exp="56"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="60"/>
                    <ReturnValue/>
                    <Condition Exp="59"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="61"/>
                    <ReturnValue/>
                    <Condition Exp="59"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="63"/>
                    <ReturnValue/>
                    <Condition Exp="62"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="64"/>
                    <ReturnValue/>
                    <Condition Exp="62"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="66"/>
                    <ReturnValue/>
                    <Condition Exp="65"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="67"/>
                    <ReturnValue/>
                    <Condition Exp="65"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="68"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End SetParam XmlCnt RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="69"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="70"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="L">
                    <Condition Exp="71"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="72"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="73"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="75"/>
                    <ReturnValue/>
                    <Condition Exp="74"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="83"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=" **** Schema  Destination ****"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="84"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="B"/>
                    <WithValue val="85"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="86"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="1"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <RaiseEvent>
                    <Event>
                      <EventType val="P"/>
                      <Exp val="5"/>
                      <PublicObject/>
                    </Event>
                    <Wait val="89"/>
                    <Arguments>
                      <Argument>
                        <id val="0"/>
                        <Expression val="6"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="7"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Skip val="Y"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="8"/>
                        <Skip val="N"/>
                      </Argument>
                    </Arguments>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </RaiseEvent>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Temp SetParam TP   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="9"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="10"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="11"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="14"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="15"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="16"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="19"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="20"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="21"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="24"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="25"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="26"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="29"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="30"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="31"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="34"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="35"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="36"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Temp SetParam TP   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Temp SetParam TS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="17"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="18"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="22"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="23"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="27"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="28"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="32"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="33"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="37"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="38"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Temp SetParam TS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="XMLCnt(0,1,'/Envelope')=0"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="SetParam('Error',455)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source XML is not well-formed.'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="'SaveInternalMSG'"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="15"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="'txt'"/>
              <ExpAttribute val="T"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="SetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite',GetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite',GetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="SetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="16">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="17">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value',GetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="18">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value',GetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="19">
              <ExpSyntax val="SetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="20">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="21">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="22">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',GetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="23">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',GetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="24">
              <ExpSyntax val="SetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="25">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="26">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="27">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse',GetParam('Temp_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="28">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse',GetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body/createOrganizationResponse_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="29">
              <ExpSyntax val="SetParam('Temp_1_S_2_7_12_1_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_7_12_1_Envelope/Body'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="30">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_7_12_1_Envelope/Body'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="31">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="32">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body',GetParam('Temp_1_S_2_7_12_1_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="33">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body',GetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="34">
              <ExpSyntax val="SetParam('Temp_1_S_2_7_12_1_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_7_12_1_Envelope'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="35">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_7_12_1_Envelope'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="36">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="37">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope',GetParam('Temp_1_S_2_7_12_1_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="38">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope',GetParam('Temp_XMLCnt_1_S_2_7_12_1_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="39">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="40">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="41">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="42">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="43">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="44">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="45">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="46">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="47">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="48">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="49">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="50">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="51">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="52">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope',XMLCnt(0,1,'/Envelope'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="53">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="54">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope',GetParam('S_2_7_12_1_Envelope')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="55">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body',XMLCnt(0,1,'/Envelope['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope'),''))&amp;']/Body'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="56">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="57">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body',GetParam('S_2_7_12_1_Envelope/Body')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="58">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse',XMLCnt(0,1,'/Envelope['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope'),''))&amp;']/Body['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body'),''))&amp;']/createOrganizationResponse'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="59">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="60">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse',GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="61">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',XMLCnt(0,1,'/Envelope['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope'),''))&amp;']/Body['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body'),''))&amp;']/createOrganizationResponse['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse'),''))&amp;']/result'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="62">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="63">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result',GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="64">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value',XMLCnt(0,1,'/Envelope['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope'),''))&amp;']/Body['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body'),''))&amp;']/createOrganizationResponse['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse'),''))&amp;']/result['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'),''))&amp;']/Value'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="65">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="66">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value',GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="67">
              <ExpSyntax val="SetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite',XMLCnt(0,1,'/Envelope['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope'),''))&amp;']/Body['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body'),''))&amp;']/createOrganizationResponse['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse'),''))&amp;']/result['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'),''))&amp;']/Value['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value'),''))&amp;']/PartySite'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="68">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite',GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="69">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartyUsageAssignment',1)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="70">
              <ExpSyntax val="SetParam('Loopcnt_1',1)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="71">
              <ExpSyntax val="LoopCounter() &lt;= XMLCnt(0,1,'/Envelope[1]/Body[1]/createOrganizationResponse[1]/result['&amp;Trim(Str(GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'),''))&amp;']/Value[1]/PartyUsageAssignment') AND Not('TRUE'LOG)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="72">
              <ExpSyntax val="SetParam('Loopcnt_1',LoopCounter()+1)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="73">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartyUsageAssignment',LoopCounter()+1)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="74">
              <ExpSyntax val="Not('TRUE'LOG)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="75">
              <ExpSyntax val="SetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartyUsageAssignment',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="76">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="77">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="78">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="79">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body/createOrganizationResponse')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="80">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope/Body')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope/Body')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="81">
              <ExpSyntax val="GetParam('S_2_7_12_1_Envelope')&gt;=GetParam('XMLCnt_S_2_7_12_1_Envelope')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="82">
              <ExpSyntax val="(ExpCalc('76'EXP)  AND ExpCalc('77'EXP)  AND ExpCalc('78'EXP)  AND ExpCalc('79'EXP)  AND ExpCalc('80'EXP)  AND ExpCalc('81'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="83">
              <ExpSyntax val="GetParam('XMLCnt_S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite')&gt;0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="84">
              <ExpSyntax val="SetParam ('C.PartySiteId',GetParam ('C.PartySiteId')&amp;','&amp;Trim (xmlget(0,1,'/Envelope['&amp;trim(str(getparam('S_2_7_12_1_Envelope'),''))&amp;']'&amp;'/Body['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body'),''))&amp;']'&amp;'/createOrganizationResponse['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body/createOrganizationResponse'),''))&amp;']'&amp;'/result['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result'),''))&amp;']'&amp;'/Value['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value'),''))&amp;']'&amp;'/PartySite['&amp;trim(str(getparam('S_2_7_12_1_Envelope/Body/createOrganizationResponse/result/Value/PartySite'),''))&amp;']'&amp;'/PartySiteId','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="85">
              <ExpSyntax val="rTrim( Trim (GetParam ('C.PartySiteId')) )"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="86">
              <ExpSyntax val="SetParam('C.PartySiteId',IF(rTrim( B )&lt;&gt;'',rTrim( B ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
