<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models>
      <Object name="Blob_Binary">
        <PropertyList model="FIELD">
          <Model attr_obj="FIELD_BLOB"/>
          <_FieldStyle val="1"/>
        </PropertyList>
      </Object>
    </Models>
  </ModelsRepository>
  <DataSourceRepository>
    <DataObjects>
      <DataObject PhysicalName="U.LocationDetails" Resident="N" data_source="Memory" name="U.LocationDetails">
        <Encrypt val="N"/>
        <Cache val="D"/>
        <IdentifyRowModifications val="U"/>
        <HasHint val="Y"/>
        <Cursor val="D"/>
        <CheckExistence val="D"/>
        <ObjectType val="T"/>
        <Owner/>
        <Position val="D"/>
        <PositionIndex val="-1"/>
        <RowLength val="0"/>
        <ColumnsLastIsn val="0"/>
        <MetaTreeRTIndex val="-1"/>
        <Columns>
          <Column id="1" name="CustomerNumber">
            <PropertyList model="FIELD" xmlns="NS_Datasource">
              <Model attr_obj="FIELD_UNICODE"/>
              <DefaultValue/>
              <StoredAs val="31"/>
              <Size val="60"/>
              <_Flip/>
              <_FieldStyle val="1"/>
              <DbColumnName val="CustomerNumber"/>
              <Picture valUnicode="30"/>
              <Definition val="2"/>
              <_FieldPhysical Name="CustomerNumber" PIC_U="30" Size="60" attribute="A" allowed_null="N" context_cookies="Y" database_definition="2" storage="31" translate="1"/>
            </PropertyList>
          </Column>
          <Column id="2" name="LocatioNumber">
            <PropertyList model="FIELD" xmlns="NS_Datasource">
              <Model attr_obj="FIELD_UNICODE"/>
              <DefaultValue/>
              <StoredAs val="31"/>
              <Size val="60"/>
              <_Flip/>
              <_FieldStyle val="1"/>
              <DbColumnName val="LocatioNumber"/>
              <Picture valUnicode="30"/>
              <Definition val="2"/>
              <_FieldPhysical Name="LocatioNumber" PIC_U="30" Size="60" attribute="A" allowed_null="N" context_cookies="Y" database_definition="2" storage="31" translate="1"/>
            </PropertyList>
          </Column>
          <Column id="3" name="PartySiteNumber">
            <PropertyList model="FIELD" xmlns="NS_Datasource">
              <Model attr_obj="FIELD_UNICODE"/>
              <DefaultValue/>
              <StoredAs val="31"/>
              <Size val="60"/>
              <_Flip/>
              <_FieldStyle val="1"/>
              <DbColumnName val="PartySiteNumber"/>
              <Picture valUnicode="30"/>
              <Definition val="2"/>
              <_FieldPhysical Name="PartySiteNumber" PIC_U="30" Size="60" attribute="A" allowed_null="N" context_cookies="Y" database_definition="2" storage="31" translate="1"/>
            </PropertyList>
          </Column>
          <Column id="4" name="BusinessManager">
            <PropertyList model="FIELD" xmlns="NS_Datasource">
              <Model attr_obj="FIELD_UNICODE"/>
              <DefaultValue/>
              <StoredAs val="31"/>
              <Size val="60"/>
              <_Flip/>
              <_FieldStyle val="1"/>
              <DbColumnName val="BusinessManager"/>
              <Picture valUnicode="30"/>
              <Definition val="2"/>
              <_FieldPhysical Name="BusinessManager" PIC_U="30" Size="60" attribute="A" allowed_null="N" context_cookies="Y" database_definition="2" storage="31" translate="1"/>
            </PropertyList>
          </Column>
        </Columns>
        <Indexes>
          <Index id="1" name="Field1K1">
            <Mode/>
            <Order/>
            <Range/>
            <IndexType/>
            <HasHint/>
            <Clustered/>
            <DropOnReindex/>
            <Primary/>
            <Segments>
              <Segment>
                <Size val="60"/>
                <Column val="1"/>
                <Order val="A"/>
              </Segment>
            </Segments>
          </Index>
          <Index id="2" name="Field2K2">
            <Mode/>
            <Order/>
            <Range/>
            <IndexType/>
            <HasHint/>
            <Clustered/>
            <DropOnReindex/>
            <Primary/>
            <Segments>
              <Segment>
                <Size val="60"/>
                <Column val="2"/>
                <Order val="A"/>
              </Segment>
            </Segments>
          </Index>
          <Index id="3" name="Field3K3">
            <Mode/>
            <Order/>
            <Range/>
            <IndexType/>
            <HasHint/>
            <Clustered/>
            <DropOnReindex/>
            <Primary/>
            <Segments>
              <Segment>
                <Size val="60"/>
                <Column val="3"/>
                <Order val="A"/>
              </Segment>
            </Segments>
          </Index>
        </Indexes>
      </DataObject>
    </DataObjects>
  </DataSourceRepository>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="U.LocationDetails">
          <Public val="U.LocationDetails"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr MgAttr="0"/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="738445" _time="81487" date="17//10//2022" time="22:38:07.2462723"/>
        </Header>
        <ReturnValueExpression val="1"/>
        <Resource>
          <Columns>
            <Column id="1" name="PI_Instance Name">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_UNICODE"/>
                <StoredAs/>
                <Size/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="100"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="2" name="PIO_UDS Content">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="3" name="PI_Function">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="2"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="4" name="PI_LocateFieldName">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_UNICODE"/>
                <StoredAs/>
                <Size/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="30"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="5" name="PI_LocateFieldValue (Dpl)">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_UNICODE"/>
                <StoredAs/>
                <Size/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="1000"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="6" name="PI_Recordset">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <CellModel attr_obj="FIELD_BLOB" comp="-1" obj="1"/>
                <StoredAs val="33"/>
                <Size/>
                <_FieldStyle val="4"/>
                <Content val="1"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="7" name="PI_SingleFieldName">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_UNICODE"/>
                <StoredAs/>
                <Size/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="30"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="8" name="PIO_SingleFieldValue">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="34"/>
                <Size/>
                <_FieldStyle val="1"/>
                <Content val="2"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="9" name="PI_Clear?">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_LOGICAL"/>
                <StoredAs/>
                <Size/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="5"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="10" name="PO_ReturnCode">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="5"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="11" name="V_MtblSet RC">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="2"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="12" name="V_Logical RC">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_LOGICAL"/>
                <StoredAs/>
                <Size/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="5"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="13" name="V_RecCounter">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="12"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="14" name="V_XmlGetBlobUniCode">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="34"/>
                <Size/>
                <_FieldStyle val="1"/>
                <Content val="2"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
          </Columns>
        </Resource>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <_TotalVariabls val="14"/>
            <_TotalVirtuals val="4"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Select Name="A">
                  <ASS/>
                  <Column val="1"/>
                  <Type val="V"/>
                  <IsParameter val="Y"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="B">
                  <ASS/>
                  <Column val="2"/>
                  <Type val="V"/>
                  <IsParameter val="Y"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="C">
                  <ASS/>
                  <Column val="3"/>
                  <Type val="V"/>
                  <IsParameter val="Y"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="D">
                  <ASS/>
                  <Column val="4"/>
                  <Type val="V"/>
                  <IsParameter val="Y"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="E">
                  <ASS/>
                  <Column val="5"/>
                  <Type val="V"/>
                  <IsParameter val="Y"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="F">
                  <ASS/>
                  <Column val="6"/>
                  <Type val="V"/>
                  <IsParameter val="Y"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="G">
                  <ASS/>
                  <Column val="7"/>
                  <Type val="V"/>
                  <IsParameter val="Y"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="H">
                  <ASS/>
                  <Column val="8"/>
                  <Type val="V"/>
                  <IsParameter val="Y"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="I">
                  <ASS/>
                  <Column val="9"/>
                  <Type val="V"/>
                  <IsParameter val="Y"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="J">
                  <ASS/>
                  <Column val="10"/>
                  <Type val="V"/>
                  <IsParameter val="Y"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Select Name="K">
                  <ASS/>
                  <Column val="11"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="L">
                  <ASS/>
                  <Column val="12"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="M">
                  <ASS/>
                  <Column val="13"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="N">
                  <ASS/>
                  <Column val="14"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="Insert"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="11"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="12"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="J"/>
                  <WithValue val="13"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="Update"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                  <Condition Exp="14"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="15"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="2"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="J"/>
                  <WithValue val="17"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition Exp="16"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="J"/>
                  <WithValue val="18"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="Delete"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                  <Condition Exp="19"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="20"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="3"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="J"/>
                  <WithValue val="22"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition Exp="21"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="J"/>
                  <WithValue val="23"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="GetValue"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                  <Condition Exp="24"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="25"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="4"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="J"/>
                  <WithValue val="26"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="SetXml"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                  <Condition Exp="27"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="6"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="GetXml"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                  <Condition Exp="28"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="29"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="7"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="B"/>
                  <WithValue val="30"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="SetValue"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                  <Condition Exp="31"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Update>
                  <Variable val="M"/>
                  <WithValue val="2"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="Function (0) - Clear"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="3"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="4"/>
                  <ReturnValue val="L"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="J"/>
                  <WithValue val="5"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="Function (7) - UDSSet"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="6"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="K"/>
                  <WithValue val="7"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="J"/>
                  <WithValue val="8"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="Function (8) - UDSGet"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="B"/>
                  <WithValue val="10"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition Exp="9"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="MTblGet ('1'DSOURCE,RTrim (A))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="0"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="I OR C =6"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="DbDel ('1'DSOURCE,RTrim (A))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="IF (L,0,1)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="C =7"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="MTblSet (B,'1'DSOURCE,RTrim (A),2)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="IF (K=0,0,10+ABS (K))"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="C=8"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="MTblGet ('1'DSOURCE,RTrim (A))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="C =1"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="VecSize (F)&gt;0 OR RTrim (G)&lt;&gt;'' AND RTrim (H)&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="2"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="C =2"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="RTrim (D)&lt;&gt;'' AND (VecSize (F)&gt;0 OR RTrim (G)&lt;&gt;'' AND RTrim (H)&lt;&gt;'')"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="M=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="80"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="18">
            <ExpSyntax val="3"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="19">
            <ExpSyntax val="C =3"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="20">
            <ExpSyntax val="RTrim (D)&lt;&gt;'' "/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="21">
            <ExpSyntax val="M=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="22">
            <ExpSyntax val="80"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="23">
            <ExpSyntax val="4"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="24">
            <ExpSyntax val="C =4"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="25">
            <ExpSyntax val="RTrim (D)&lt;&gt;'' AND RTrim (G )&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="26">
            <ExpSyntax val="5"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="27">
            <ExpSyntax val="C =9"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="28">
            <ExpSyntax val="C =10"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="29">
            <ExpSyntax val="DbDel ('1'DSOURCE,RTrim (A))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="30">
            <ExpSyntax val="MTblGet ('1'DSOURCE,RTrim (A))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="31">
            <ExpSyntax val="C =5"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <Task>
          <Header Description="Insert">
            <Public val="Insert"/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738445" _time="81487" date="17//10//2022" time="22:38:07.2802696"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <DB>
              <DataObject obj="1"/>
              <Exp val="1"/>
              <Access val="W"/>
              <Share val="W"/>
              <Open val="N"/>
              <Cache val="Y"/>
              <IdentifyRowModifications val="84"/>
            </DB>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB obj="1"/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="C"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="4"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC IDX="1" Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="O">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="P">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="Q">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="R">
                    <ASS/>
                    <Column val="4"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="2"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="O"/>
                    <WithValue val="3"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="P"/>
                    <WithValue val="4"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="Q"/>
                    <WithValue val="5"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="R"/>
                    <WithValue val="6"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                    <Condition Exp="7"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="O"/>
                    <WithValue val="8"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                    <Condition Exp="9"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="P"/>
                    <WithValue val="10"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                    <Condition Exp="11"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="Q"/>
                    <WithValue val="12"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                    <Condition Exp="13"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="R"/>
                    <WithValue val="14"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="RTrim (A)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="VecSize(F) &gt; 0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="EvalStr (VecGet (F,1),'')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="EvalStr (VecGet (F,2),'')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="EvalStr (VecGet (F,3),'')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="EvalStr (VecGet (F,4),'')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="RTrim (G) = 'CustomerNumber'"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="RTrim(H)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="RTrim (G) = 'LocatioNumber'"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="RTrim(H)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="RTrim (G) = 'PartySiteNumber'"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="RTrim(H)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="RTrim (G) = 'BusinessManager'"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="RTrim(H)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
        <Task>
          <Header Description="Update">
            <Public val="Update"/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738445" _time="81487" date="17//10//2022" time="22:38:07.2842677"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <DB>
              <DataObject obj="1"/>
              <Exp val="1"/>
              <Access val="W"/>
              <Share val="W"/>
              <Open val="N"/>
              <Cache val="Y"/>
              <IdentifyRowModifications val="84"/>
            </DB>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB obj="1"/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="N"/>
            <EvaluateEndCondition val="B"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="4"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC IDX="1" Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="O">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Range MAX="2" MIN="2"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="P">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Range MAX="3" MIN="3"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="Q">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Range MAX="4" MIN="4"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="R">
                    <ASS/>
                    <Column val="4"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Range MAX="5" MIN="5"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="M"/>
                    <WithValue val="6"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="7"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="O"/>
                    <WithValue val="8"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="P"/>
                    <WithValue val="9"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="Q"/>
                    <WithValue val="10"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="R"/>
                    <WithValue val="11"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                    <Condition Exp="12"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="O"/>
                    <WithValue val="13"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                    <Condition Exp="14"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="P"/>
                    <WithValue val="15"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                    <Condition Exp="16"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="Q"/>
                    <WithValue val="17"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="E">
                    <Condition Exp="18"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="R"/>
                    <WithValue val="19"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="RTrim (A)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="CndRange (RTrim (D)='CustomerNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="CndRange (RTrim (D)='LocatioNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="CndRange (RTrim (D)='PartySiteNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="CndRange (RTrim (D)='BusinessManager',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="M+1"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="VecSize(F) &gt; 0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="RTrim(VecGet (F,1))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="RTrim(VecGet (F,2))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="RTrim(VecGet (F,3))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="RTrim(VecGet (F,4))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="RTrim (G) = 'CustomerNumber'"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="RTrim(H)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="RTrim (G) = 'LocatioNumber'"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="RTrim(H)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="16">
              <ExpSyntax val="RTrim (G) = 'PartySiteNumber'"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="17">
              <ExpSyntax val="RTrim(H)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="18">
              <ExpSyntax val="RTrim (G) = 'BusinessManager'"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="19">
              <ExpSyntax val="RTrim(H)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <VarRangeInfo Mode="E" VarRangeVeeIsn="1" id="1"/>
          <VarRangeInfo Mode="E" VarRangeVeeIsn="2" id="2"/>
          <VarRangeInfo Mode="E" VarRangeVeeIsn="3" id="3"/>
          <VarRangeInfo Mode="E" VarRangeVeeIsn="4" id="4"/>
        </Task>
        <Task>
          <Header Description="Delete">
            <Public val="Delete"/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738445" _time="81487" date="17//10//2022" time="22:38:07.2892715"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <DB>
              <DataObject obj="1"/>
              <Exp val="1"/>
              <Access val="W"/>
              <Share val="W"/>
              <Open val="N"/>
              <Cache val="Y"/>
              <IdentifyRowModifications val="84"/>
            </DB>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB obj="1"/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="N"/>
            <EvaluateEndCondition val="B"/>
            <InitialMode val="D"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="4"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC IDX="1" Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="O">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Range MAX="2" MIN="2"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="P">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Range MAX="3" MIN="3"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="Q">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Range MAX="4" MIN="4"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="R">
                    <ASS/>
                    <Column val="4"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Range MAX="5" MIN="5"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="M"/>
                    <WithValue val="6"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="RTrim (A)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="CndRange (RTrim (D)='CustomerNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="CndRange (RTrim (D)='LocatioNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="CndRange (RTrim (D)='PartySiteNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="CndRange (RTrim (D)='BusinessManager',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="M+1"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <VarRangeInfo Mode="E" VarRangeVeeIsn="1" id="1"/>
          <VarRangeInfo Mode="E" VarRangeVeeIsn="2" id="2"/>
          <VarRangeInfo Mode="E" VarRangeVeeIsn="3" id="3"/>
          <VarRangeInfo Mode="E" VarRangeVeeIsn="4" id="4"/>
        </Task>
        <Task>
          <Header Description="GetSingleValue">
            <Public val="GetSingleValue"/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738445" _time="81487" date="17//10//2022" time="22:38:07.2922694"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <DB>
              <DataObject obj="1"/>
              <Exp val="1"/>
              <Access val="W"/>
              <Share val="W"/>
              <Open val="N"/>
              <Cache val="Y"/>
              <IdentifyRowModifications val="84"/>
            </DB>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="4"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC IDX="1" Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <LNK Direction="A" EVL_CND="R" Mode="L">
                    <DB obj="1"/>
                    <Expanded val="1"/>
                    <Condition val="Y"/>
                  </LNK>
                </LogicLine>
                <LogicLine>
                  <Select Name="O">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Locate MAX="2" MIN="2"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="P">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Locate MAX="3" MIN="3"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="Q">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Locate MAX="4" MIN="4"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="R">
                    <ASS/>
                    <Column val="4"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Locate MAX="5" MIN="5"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <END_LINK/>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="H"/>
                    <WithValue val="7"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition Exp="6"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="H"/>
                    <WithValue val="9"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition Exp="8"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="H"/>
                    <WithValue val="11"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition Exp="10"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="H"/>
                    <WithValue val="13"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition Exp="12"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="RTrim (A)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="CndRange (RTrim (D)='CustomerNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="CndRange (RTrim (D)='LocatioNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="CndRange (RTrim (D)='PartySiteNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="CndRange (RTrim (D)='BusinessManager',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="RTrim (G)='CustomerNumber'"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="RTrim(O)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="RTrim (G)='LocatioNumber'"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="RTrim(P)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="RTrim (G)='PartySiteNumber'"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="RTrim(Q)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="RTrim (G)='BusinessManager'"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="RTrim(R)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
        <Task>
          <Header Description="GetRecSet">
            <Public val="GetRecSet"/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738445" _time="81487" date="17//10//2022" time="22:38:07.2982679"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <DB>
              <DataObject obj="1"/>
              <Exp val="1"/>
              <Access val="W"/>
              <Share val="W"/>
              <Open val="N"/>
              <Cache val="Y"/>
              <IdentifyRowModifications val="84"/>
            </DB>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="4"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC IDX="1" Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <LNK Direction="A" EVL_CND="R" Mode="L">
                    <DB obj="1"/>
                    <Expanded val="1"/>
                    <Condition val="Y"/>
                  </LNK>
                </LogicLine>
                <LogicLine>
                  <Select Name="O">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Locate MAX="2" MIN="2"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="P">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Locate MAX="3" MIN="3"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="Q">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Locate MAX="4" MIN="4"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="R">
                    <ASS/>
                    <Column val="4"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <Locate MAX="5" MIN="5"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <END_LINK/>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="B"/>
                    <WithValue val="7"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition Exp="6"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="B"/>
                    <WithValue val="9"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition Exp="8"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="B"/>
                    <WithValue val="11"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition Exp="10"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="B"/>
                    <WithValue val="13"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition Exp="12"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="RTrim (A)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="CndRange (RTrim (D)='CustomerNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="CndRange (RTrim (D)='LocatioNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="CndRange (RTrim (D)='PartySiteNumber',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="CndRange (RTrim (D)='BusinessManager',RTrim(E))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="RTrim (G)='CustomerNumber'"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="RTrim(O)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="RTrim (G)='LocatioNumber'"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="RTrim(P)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="RTrim (G)='PartySiteNumber'"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="RTrim(Q)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="RTrim (G)='BusinessManager'"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="RTrim(R)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
        <Task>
          <Header Description="SetXml">
            <Public val="SetXml"/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738445" _time="81487" date="17//10//2022" time="22:38:07.3032715"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <DB>
              <DataObject obj="1"/>
              <Exp val="1"/>
              <Access val="W"/>
              <Share val="W"/>
              <Open val="N"/>
              <Cache val="Y"/>
              <IdentifyRowModifications val="84"/>
            </DB>
            <IO Column="B">
              <Description val="InitializeUDSPackXML"/>
              <Format val="N"/>
              <Media val="V"/>
              <Access val="W"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB obj="1"/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="N"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="4"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC IDX="1" Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="O">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="P">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="Q">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="R">
                    <ASS/>
                    <Column val="4"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Evaluate>
                    <Expression val="7"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="CustomerNumber"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="8"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="9"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="10"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="LocatioNumber"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="11"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="PartySiteNumber"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="14"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="15"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="16"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="BusinessManager"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="17"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="18"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="19"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="Encoding"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="udsInformation"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="5"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="6"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="RTrim (A)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="XMLSetEncoding(0,1,'ISO-8859-1')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation','','')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/udsVariableModelName','','U.LocationDetails')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/flowVariableName','',RTrim (A))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords','','')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record','','')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field','',BlobToBase64(RTrim(O)))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[1]','Name','CustomerNumber')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[1]','Type','A')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field','',BlobToBase64(RTrim(P)))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[2]','Name','LocatioNumber')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[2]','Type','A')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field','',BlobToBase64(RTrim(Q)))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[3]','Name','PartySiteNumber')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="16">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[3]','Type','A')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="17">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field','',BlobToBase64(RTrim(R)))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="18">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[4]','Name','BusinessManager')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="19">
              <ExpSyntax val="XMLInsert(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[4]','Type','A')"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
        <Task>
          <Header Description="GetXml">
            <Public val="GetXml"/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738445" _time="81487" date="17//10//2022" time="22:38:07.3102674"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <DB>
              <DataObject obj="1"/>
              <Exp val="2"/>
              <Access val="W"/>
              <Share val="W"/>
              <Open val="N"/>
              <Cache val="Y"/>
              <IdentifyRowModifications val="84"/>
            </DB>
            <IO Column="B">
              <Description val="InitializeUDSUnPackXML"/>
              <Format val="N"/>
              <Media val="V"/>
              <Access val="R"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y" Exp="1"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="4"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC IDX="1" Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <LNK Direction="A" EVL_CND="R" Mode="A">
                    <DB obj="1"/>
                    <Expanded val="1"/>
                    <Condition Exp="3"/>
                  </LNK>
                </LogicLine>
                <LogicLine>
                  <Select Name="O">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="P">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="Q">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="R">
                    <ASS/>
                    <Column val="4"/>
                    <Type val="R"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <END_LINK/>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="CustomerNumber"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="N"/>
                    <WithValue val="4"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="O"/>
                    <WithValue val="5"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="LocatioNumber"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="N"/>
                    <WithValue val="6"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="P"/>
                    <WithValue val="7"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="PartySiteNumber"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="N"/>
                    <WithValue val="8"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="Q"/>
                    <WithValue val="9"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="BusinessManager"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="N"/>
                    <WithValue val="10"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="R"/>
                    <WithValue val="11"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="Counter(0)&gt;=XMLCnt(0,1,'/udsInformation/instanceRecords/record')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="RTrim (A)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="XMLCnt(0,1,'/udsInformation/instanceRecords/record')&gt;0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="BlobFromBase64(UnicodeToANSI(XMLGet(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[1]'),0))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="RTrim(N)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="BlobFromBase64(UnicodeToANSI(XMLGet(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[2]'),0))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="RTrim(N)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="BlobFromBase64(UnicodeToANSI(XMLGet(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[3]'),0))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="RTrim(N)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="BlobFromBase64(UnicodeToANSI(XMLGet(0,1,'/udsInformation/instanceRecords/record['&amp;Trim(Str(Counter(0),'12'))&amp;']/Field[4]'),0))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="RTrim(N)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
