{
	"InvoiceNumber": "<!$MG_InvoiceNumber>",
	"InvoiceCurrency": "<!$MG_InvoiceCurrency>",
	"InvoiceAmount": <!$MG_InvoiceAmount>,
	"InvoiceDate": "<!$MG_InvoiceDate>",
	"BusinessUnit": "<!$MG_BusinessUnit>",
	"Supplier": "<!$MG_Supplier>",
	"SupplierSite": "<!$MG_SupplierSite>",
	"AccountingDate":"<!$MG_AccountingDate>",
	"InvoiceGroup": "<!$MG_InvoiceGroup>",
	"ConversionRateType": "<!$MG_ConversionRateType>",
	"ConversionDate": "<!$MG_ConversionDate>",
	"ControlAmount": "<!$MG_ControlAmount>",
	"Description": "<!$MG_Description>",
	"InvoiceType": "<!$MG_InvoiceType>",
	"LegalEntity":"<!$MG_LegalEntityIdentifier>",