package com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 *         
 *
 * This class was generated by Apache CXF 3.3.1
 * 2023-01-27T20:28:31.490+11:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/", name = "StandardReceiptService")
@XmlSeeAlso({com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class, sdo.commonj.java.ObjectFactory.class, com.oracle.xmlns.apps.financials.receivables.receipts.shared.model.flex.standardreceiptdff.ObjectFactory.class, sdo.commonj.xml.ObjectFactory.class, com.oracle.xmlns.apps.flex.financials.receivables.receipts.shared.standardreceiptservice.commonservice.applyonaccountdff.ObjectFactory.class, com.oracle.xmlns.adf.svc.types.ObjectFactory.class, ObjectFactory.class, com.oracle.xmlns.apps.flex.financials.receivables.receipts.shared.standardreceiptservice.commonservice.applyonaccountgdf.ObjectFactory.class, com.oracle.xmlns.apps.flex.financials.receivables.receipts.shared.standardreceiptservice.commonservice.activityapplicationgdf.ObjectFactory.class, com.oracle.xmlns.apps.flex.financials.receivables.receipts.shared.standardreceiptservice.commonservice.applyreceiptdff.ObjectFactory.class, com.oracle.xmlns.apps.flex.financials.receivables.receipts.shared.standardreceiptservice.commonservice.activityapplicationdff.ObjectFactory.class, com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ObjectFactory.class, sdo.commonj.ObjectFactory.class, com.oracle.xmlns.adf.svc.errors.ObjectFactory.class, com.oracle.xmlns.apps.financials.receivables.receipts.shared.model.flex.standardreceiptgdf.ObjectFactory.class})
public interface StandardReceiptService {

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getServiceLastUpdateTimeAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processReverseReceiptAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processReverseReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "processReverseReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessReverseReceiptAsync")
    public void processReverseReceiptAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "reverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ReverseReceipt> reverseReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getEntityList")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetEntityListResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public java.util.List<com.oracle.xmlns.adf.svc.types.ServiceViewInfo> getEntityList() throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processUnapplyOnAccount")
    @RequestWrapper(localName = "processUnapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyOnAccount")
    @ResponseWrapper(localName = "processUnapplyOnAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyOnAccountResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyOnAccountResult processUnapplyOnAccount(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "unapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyOnAccount> unapplyOnAccount,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processUnapplyReceipt")
    @RequestWrapper(localName = "processUnapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyReceipt")
    @ResponseWrapper(localName = "processUnapplyReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyReceiptResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyReceiptResult processUnapplyReceipt(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "unapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyReceipt> unapplyReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processApplyReceipt")
    @RequestWrapper(localName = "processApplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyReceipt")
    @ResponseWrapper(localName = "processApplyReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyReceiptResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyReceiptResult processApplyReceipt(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "applyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyReceipt> applyReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processActivityApplication")
    @RequestWrapper(localName = "processActivityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityApplication")
    @ResponseWrapper(localName = "processActivityApplicationResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityApplicationResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityApplicationResult processActivityApplication(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "activityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityApplication> activityApplication,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createApplyReceipt")
    @RequestWrapper(localName = "createApplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyReceipt")
    @ResponseWrapper(localName = "createApplyReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyReceiptResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyReceiptResult createApplyReceipt(
        @WebParam(name = "applyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyReceipt applyReceipt
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processReverseReceipt")
    @RequestWrapper(localName = "processReverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessReverseReceipt")
    @ResponseWrapper(localName = "processReverseReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessReverseReceiptResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ReverseReceiptResult processReverseReceipt(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "reverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ReverseReceipt> reverseReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processActivityUnapplicationAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processActivityUnapplicationAsync")
    @Oneway
    @RequestWrapper(localName = "processActivityUnapplicationAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityUnapplicationAsync")
    public void processActivityUnapplicationAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "activityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityUnapplication> activityUnapplication,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getDfltObjAttrHintsAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String localeName
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getEntityListAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetEntityListAsync")
    public void getEntityListAsync();

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createUnapplyReceipt")
    @RequestWrapper(localName = "createUnapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyReceipt")
    @ResponseWrapper(localName = "createUnapplyReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyReceiptResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyReceiptResult createUnapplyReceipt(
        @WebParam(name = "unapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyReceipt unapplyReceipt
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/findStandardReceiptAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/findStandardReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "findStandardReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.FindStandardReceiptAsync")
    public void findStandardReceiptAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.FindControl findControl
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processApplyOnAccountAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processApplyOnAccountAsync")
    @Oneway
    @RequestWrapper(localName = "processApplyOnAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyOnAccountAsync")
    public void processApplyOnAccountAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "applyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyOnAccount> applyOnAccount,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processApplyReceiptAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processApplyReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "processApplyReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyReceiptAsync")
    public void processApplyReceiptAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "applyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyReceipt> applyReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createApplyOnAccount")
    @RequestWrapper(localName = "createApplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyOnAccount")
    @ResponseWrapper(localName = "createApplyOnAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyOnAccountResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyOnAccountResult createApplyOnAccount(
        @WebParam(name = "applyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyOnAccount applyOnAccount
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createStandardReceiptAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createStandardReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "createStandardReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateStandardReceiptAsync")
    public void createStandardReceiptAsync(
        @WebParam(name = "standardReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.StandardReceipt standardReceipt
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createActivityApplication")
    @RequestWrapper(localName = "createActivityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityApplication")
    @ResponseWrapper(localName = "createActivityApplicationResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityApplicationResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityApplicationResult createActivityApplication(
        @WebParam(name = "activityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityApplication activityApplication
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createApplyOnAccountAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createApplyOnAccountAsync")
    @Oneway
    @RequestWrapper(localName = "createApplyOnAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyOnAccountAsync")
    public void createApplyOnAccountAsync(
        @WebParam(name = "applyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyOnAccount applyOnAccount
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createActivityApplicationAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createActivityApplicationAsync")
    @Oneway
    @RequestWrapper(localName = "createActivityApplicationAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityApplicationAsync")
    public void createActivityApplicationAsync(
        @WebParam(name = "activityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityApplication activityApplication
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processUnapplyOnAccountAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processUnapplyOnAccountAsync")
    @Oneway
    @RequestWrapper(localName = "processUnapplyOnAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyOnAccountAsync")
    public void processUnapplyOnAccountAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "unapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyOnAccount> unapplyOnAccount,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createUnapplyReceiptAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createUnapplyReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "createUnapplyReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyReceiptAsync")
    public void createUnapplyReceiptAsync(
        @WebParam(name = "unapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyReceipt unapplyReceipt
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createActivityUnapplicationAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createActivityUnapplicationAsync")
    @Oneway
    @RequestWrapper(localName = "createActivityUnapplicationAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityUnapplicationAsync")
    public void createActivityUnapplicationAsync(
        @WebParam(name = "activityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityUnapplication activityUnapplication
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getServiceLastUpdateTime")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetServiceLastUpdateTimeResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public javax.xml.datatype.XMLGregorianCalendar getServiceLastUpdateTime() throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processApplyOnAccount")
    @RequestWrapper(localName = "processApplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyOnAccount")
    @ResponseWrapper(localName = "processApplyOnAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyOnAccountResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyOnAccountResult processApplyOnAccount(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "applyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyOnAccount> applyOnAccount,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processUnapplyReceiptAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processUnapplyReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "processUnapplyReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyReceiptAsync")
    public void processUnapplyReceiptAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "unapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyReceipt> unapplyReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createReverseReceiptAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createReverseReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "createReverseReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateReverseReceiptAsync")
    public void createReverseReceiptAsync(
        @WebParam(name = "reverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ReverseReceipt reverseReceipt
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createApplyReceiptAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createApplyReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "createApplyReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyReceiptAsync")
    public void createApplyReceiptAsync(
        @WebParam(name = "applyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyReceipt applyReceipt
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getDfltObjAttrHints")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetDfltObjAttrHintsResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.adf.svc.types.ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String localeName
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processActivityUnapplication")
    @RequestWrapper(localName = "processActivityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityUnapplication")
    @ResponseWrapper(localName = "processActivityUnapplicationResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityUnapplicationResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityUnapplicationResult processActivityUnapplication(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "activityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityUnapplication> activityUnapplication,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/findStandardReceipt")
    @RequestWrapper(localName = "findStandardReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.FindStandardReceipt")
    @ResponseWrapper(localName = "findStandardReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.FindStandardReceiptResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.StandardReceiptResult findStandardReceipt(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.FindControl findControl
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createActivityUnapplication")
    @RequestWrapper(localName = "createActivityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityUnapplication")
    @ResponseWrapper(localName = "createActivityUnapplicationResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityUnapplicationResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityUnapplicationResult createActivityUnapplication(
        @WebParam(name = "activityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityUnapplication activityUnapplication
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processActivityApplicationAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processActivityApplicationAsync")
    @Oneway
    @RequestWrapper(localName = "processActivityApplicationAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityApplicationAsync")
    public void processActivityApplicationAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.lang.String changeOperation,
        @WebParam(name = "activityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        java.util.List<com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityApplication> activityApplication,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.adf.svc.types.ProcessControl processControl
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createReverseReceipt")
    @RequestWrapper(localName = "createReverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateReverseReceipt")
    @ResponseWrapper(localName = "createReverseReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateReverseReceiptResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ReverseReceiptResult createReverseReceipt(
        @WebParam(name = "reverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ReverseReceipt reverseReceipt
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createUnapplyOnAccountAsync")
    @Action(input = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createUnapplyOnAccountAsync")
    @Oneway
    @RequestWrapper(localName = "createUnapplyOnAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyOnAccountAsync")
    public void createUnapplyOnAccountAsync(
        @WebParam(name = "unapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyOnAccount unapplyOnAccount
    );

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createUnapplyOnAccount")
    @RequestWrapper(localName = "createUnapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyOnAccount")
    @ResponseWrapper(localName = "createUnapplyOnAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyOnAccountResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyOnAccountResult createUnapplyOnAccount(
        @WebParam(name = "unapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyOnAccount unapplyOnAccount
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createStandardReceipt")
    @RequestWrapper(localName = "createStandardReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateStandardReceipt")
    @ResponseWrapper(localName = "createStandardReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateStandardReceiptResponse")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    public com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.StandardReceiptResult createStandardReceipt(
        @WebParam(name = "standardReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.StandardReceipt standardReceipt
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;
}
