<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models/>
  </ModelsRepository>
  <DataSourceRepository/>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="map_1_20_228">
          <Public val="map_1_20_228"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="738228" _time="67579" date="14//3//2022" time="18:46:19.6693063"/>
        </Header>
        <ReturnValueExpression/>
        <Resource>
          <Columns>
            <Column id="1" name="1_Destination_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="2" name="1_Destination_XMLIoPtrDll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole val="3"/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="3" name="1_Destination_XMLEncoding_w_Dll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_ALPHA"/>
                <StoredAs val="2"/>
                <Size val="3"/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
          </Columns>
        </Resource>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <_TotalVariabls val="3"/>
            <_TotalVirtuals val="3"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Select Name="A">
                  <ASS/>
                  <Column val="1"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="B">
                  <ASS/>
                  <Column val="2"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="C">
                  <ASS/>
                  <Column val="3"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="1"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="3"/>
                  <ReturnValue/>
                  <Condition Exp="2"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="4"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="5"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                  <Condition Exp="6"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </BLOCK>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="7"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="8"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="9"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="10"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="11"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="12"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="13"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <END_BLK/>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="14"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="15"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="17"/>
                  <ReturnValue/>
                  <Condition Exp="16"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="SetParam('xmlErr',' ')"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="FileSize(getFullPath(TranslateNR(Trim (EnvVal ('currentprojectdir')&amp;'Files\RoleCall_FU\Fusion\DimensionMaster\7.SIS Create Code Combination\Request\Request.xml'))))&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="FileSize(getFullPath(TranslateNR(Trim (EnvVal ('currentprojectdir')&amp;'Files\RoleCall_FU\Fusion\DimensionMaster\7.SIS Create Code Combination\Request\Request.xml'))))=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',' Schema XML_2 (id=2), '&amp;MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="SetParam ('000000000001000000000020F.Request',A)"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="GetParam('xmlErr')&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="SetParam('C.sys.LastErrorInfo',GetParam('xmlErr'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <Task>
          <Header Description="NoSource_HyrarchiDestination">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="738228" _time="67579" date="14//3//2022" time="18:46:19.6693063"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO>
              <Description val="xmlSource_1_20_228_2"/>
              <IOExpression val="1"/>
              <OpenPrintDialog val="N"/>
              <PaperSize val="68"/>
              <Format val="N"/>
              <Media val="D"/>
              <Access val="R"/>
              <Copies val="1"/>
              <Orientation val="P"/>
              <PrintPreview val="N"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="B"/>
                    <WithValue val="10"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="11"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="14"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="15"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="16"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="17"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="C"/>
                    <WithValue val="18"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <CallTask>
                    <OperationType val="T"/>
                    <TaskID comp="-1" obj="1"/>
                    <Lock val="N"/>
                    <Arguments/>
                    <Wait val="Y"/>
                    <SyncData val="N"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </CallTask>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="19"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="20"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="A"/>
                    <WithValue val="21"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="22"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="2"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="0"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="5"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <RaiseEvent>
                    <Event>
                      <EventType val="P"/>
                      <Exp val="6"/>
                      <PublicObject/>
                    </Event>
                    <Wait val="89"/>
                    <Arguments>
                      <Argument>
                        <id val="0"/>
                        <Expression val="7"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="8"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Skip val="Y"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="9"/>
                        <Skip val="N"/>
                      </Argument>
                    </Arguments>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </RaiseEvent>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="TranslateNR(getFullPath(EnvVal ('currentprojectdir')&amp;'Files\RoleCall_FU\Fusion\DimensionMaster\7.SIS Create Code Combination\Request\Request.xml'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="XMLCnt(0,1,'/Envelope')=0"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="SetParam('Error',455)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam ('C.sys.ErrorDescription',' Schema XML_2 (id=2), '&amp;MlsTrans ('Source XML is not well-formed.'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="'SaveInternalMSG'"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="15"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="'txt'"/>
              <ExpAttribute val="T"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="UDF ('ibiowritter.openio',Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')),'wb', IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','16',IF(Trim(SharedValGet ('IBProjectEncoding'))='UTF-8','8','A')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="UDF ('ibiowritter.writeLnAsIs'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'&lt;?xml version=&quot;1.0&quot; encoding=&quot;'&amp;Trim(SharedValGet('IBProjectEncoding'))&amp;'&quot; standalone=&quot;no&quot; ?&gt;',B)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'soap','http://www.w3.org/2003/05/soap-envelope',B)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'xs','http://www.w3.org/2001/XMLSchema',B)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'app1','http://xmlns.oracle.com/oxp/service/PublicReportService',B)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'ns1','http://xmlns.oracle.com/oxp/service/PublicReportService',B)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="16">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'msdata','urn:schemas-microsoft-com:xml-msdata',B)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="17">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'xsi','http://www.w3.org/2001/XMLSchema-instance',B)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="18">
              <ExpSyntax val="IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',IF(Trim(SharedValGet ('IBProjectEncoding'))='UTF-8','_8',''))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="19">
              <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(C),'L','','','',B,0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="20">
              <ExpSyntax val="UDF ('ibiowritter.closeio',B)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="21">
              <ExpSyntax val="File2Blb(Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="22">
              <ExpSyntax val="FileDelete(Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <Task>
            <Header Description="soap:Envelope">
              <Public/>
              <ExecutionRight/>
              <Resident val="N"/>
              <SQL val="N"/>
              <ReturnValue>
                <ReturnValueAttr/>
                <ParametersAttributes/>
              </ReturnValue>
              <SqlWhereExist val="N"/>
              <TaskType val="B"/>
              <External val="Y"/>
              <LastModified _date="738228" _time="67579" date="14//3//2022" time="18:46:19.6693063"/>
            </Header>
            <ReturnValueExpression/>
            <Resource>
              <Columns>
                <Column id="1" name="D_1_Header">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="2" name="RecordsExistIndication">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_LOGICAL"/>
                    <StoredAs val="15"/>
                    <Size val="28"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="5"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
              </Columns>
            </Resource>
            <Information>
              <Key>
                <Column/>
                <Mode val="N"/>
              </Key>
              <DB/>
              <Sort>
                <CLS val="A"/>
              </Sort>
              <ForceRecordDelete DEL="N"/>
              <EndTaskCondition val="Y" Exp="12"/>
              <EvaluateEndCondition val="A"/>
              <InitialMode val="M"/>
              <Locate Direction="A"/>
              <Range Direction="A"/>
              <VarRange/>
              <TaskProperties>
                <SelectionTable val="N"/>
                <ConfirmUpdate CNFU="N"/>
                <ConfirmCancel val="N"/>
                <ErrorStrategy val="R"/>
                <LockingStrategy val="M"/>
                <CacheStrategy val="T"/>
                <ForceRecordSuffix val="N"/>
                <TransactionMode val="P"/>
                <TransactionBegin val="N"/>
                <PreloadView val="N"/>
                <KeepCreatedContext val="N"/>
              </TaskProperties>
              <SIDE_WIN>
                <AllowOptions val="N"/>
                <AllowQuery val="Y"/>
                <AllowModify val="Y"/>
                <AllowCreate val="Y"/>
                <AllowDelete val="Y"/>
                <AllowLocate val="Y"/>
                <AllowRange val="Y"/>
                <AllowIndexChange val="Y"/>
                <AllowSorting val="Y"/>
                <AllowIOFiles val="Y"/>
                <RecordCycle val="Y"/>
                <AllowEvents val="Y"/>
                <AllowIndexOptimization val="Y"/>
                <AllowLocationInQuery val="Y"/>
                <AllowPrintingData val="N"/>
              </SIDE_WIN>
              <WIN>
                <OpenTaskWindow val="N"/>
                <CloseTaskWindow val="Y"/>
                <ForegroundWindow val="Y"/>
                <FlipFld val="N"/>
                <RefreshTaskWindow ReturnValue="N"/>
              </WIN>
              <BOX>
                <Direction val="V"/>
              </BOX>
            </Information>
            <TaskLogic>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="M"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <_TotalVariabls val="2"/>
                <_TotalVirtuals val="2"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <DATAVIEW_SRC Type="M">
                      <Condition val="N"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </DATAVIEW_SRC>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="D">
                      <ASS/>
                      <Column val="1"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="E">
                      <ASS/>
                      <Column val="2"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Block SetParam RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                      <Condition Exp="6"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </BLOCK>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="7"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <END_BLK/>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Block SetParam RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="9"/>
                      <ReturnValue/>
                      <Condition Exp="8"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="10"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End SetParam XmlCnt RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                      <Condition Exp="13"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </BLOCK>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=" **** Schema  Destination ****"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="14"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="D"/>
                      <WithValue val="15"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="16"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="E"/>
                      <WithValue val="18"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition Exp="17"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <CallTask>
                      <OperationType val="T"/>
                      <TaskID comp="-1" obj="1"/>
                      <Lock val="N"/>
                      <Arguments/>
                      <Wait val="Y"/>
                      <SyncData val="N"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </CallTask>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <END_BLK/>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Temp SetParam TP   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="1"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="2"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="3"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Temp SetParam TP   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Temp SetParam TS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="4"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="5"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Temp SetParam TS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
            </TaskLogic>
            <TaskForms>
              <FormEntry _last_test_id="1">
                <PropertyList model="FORM_GUI0">
                  <Width/>
                  <Height/>
                  <_Comment/>
                  <FormName valUnicode="Empty Program"/>
                </PropertyList>
              </FormEntry>
            </TaskForms>
            <Expressions>
              <Expression val="1">
                <ExpSyntax val="SetParam('Temp_2_S_1_20_228_2_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_20_228_2_Envelope'))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="2">
                <ExpSyntax val="SetParam('Temp_XMLCnt_2_S_1_20_228_2_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_20_228_2_Envelope'))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="3">
                <ExpSyntax val="SetParam('S_1_20_228_2_Envelope',0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="4">
                <ExpSyntax val="SetParam('S_1_20_228_2_Envelope',GetParam('Temp_2_S_1_20_228_2_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="5">
                <ExpSyntax val="SetParam('XMLCnt_S_1_20_228_2_Envelope',GetParam('Temp_XMLCnt_2_S_1_20_228_2_Envelope_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="6">
                <ExpSyntax val="GetParam('S_1_20_228_2_Envelope')&gt;=GetParam('XMLCnt_S_1_20_228_2_Envelope')"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="7">
                <ExpSyntax val="SetParam('S_1_20_228_2_Envelope',0)"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="8">
                <ExpSyntax val="GetParam('S_1_20_228_2_Envelope') =0"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="9">
                <ExpSyntax val="SetParam('XMLCnt_S_1_20_228_2_Envelope',XMLCnt(1,1,'/Envelope'))"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="10">
                <ExpSyntax val="SetParam('S_1_20_228_2_Envelope',GetParam('S_1_20_228_2_Envelope')+1)"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="11">
                <ExpSyntax val="GetParam('S_1_20_228_2_Envelope')&gt;=GetParam('XMLCnt_S_1_20_228_2_Envelope')"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="12">
                <ExpSyntax val="(ExpCalc('11'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="13">
                <ExpSyntax val="GetParam('XMLCnt_S_1_20_228_2_Envelope')&gt;0"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="14">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(C),'C','soap:Envelope','soap:Envelope','',B,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="15">
                <ExpSyntax val="xmlget(1,1,'/Envelope['&amp;trim(str(getparam('S_1_20_228_2_Envelope'),''))&amp;']'&amp;'/Header','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="16">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(C),'S','soap:Header','soap:Envelope/soap:Header',rtrim(D),B,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="17">
                <ExpSyntax val="NOT(E)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="18">
                <ExpSyntax val="'True'Log"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
            </Expressions>
            <Task>
              <Header Description="soap:Envelope/soap:Body">
                <Public/>
                <ExecutionRight/>
                <Resident val="N"/>
                <SQL val="N"/>
                <ReturnValue>
                  <ReturnValueAttr/>
                  <ParametersAttributes/>
                </ReturnValue>
                <SqlWhereExist val="N"/>
                <TaskType val="B"/>
                <External val="Y"/>
                <LastModified _date="738228" _time="67579" date="14//3//2022" time="18:46:19.6693063"/>
              </Header>
              <ReturnValueExpression/>
              <Resource>
                <Columns>
                  <Column id="1" name="RecordsExistIndication">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_LOGICAL"/>
                      <StoredAs val="15"/>
                      <Size val="28"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="5"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                </Columns>
              </Resource>
              <Information>
                <Key>
                  <Column/>
                  <Mode val="N"/>
                </Key>
                <DB/>
                <Sort>
                  <CLS val="A"/>
                </Sort>
                <ForceRecordDelete DEL="N"/>
                <EndTaskCondition val="Y" Exp="12"/>
                <EvaluateEndCondition val="A"/>
                <InitialMode val="M"/>
                <Locate Direction="A"/>
                <Range Direction="A"/>
                <VarRange/>
                <TaskProperties>
                  <SelectionTable val="N"/>
                  <ConfirmUpdate CNFU="N"/>
                  <ConfirmCancel val="N"/>
                  <ErrorStrategy val="R"/>
                  <LockingStrategy val="M"/>
                  <CacheStrategy val="T"/>
                  <ForceRecordSuffix val="N"/>
                  <TransactionMode val="P"/>
                  <TransactionBegin val="N"/>
                  <PreloadView val="N"/>
                  <KeepCreatedContext val="N"/>
                </TaskProperties>
                <SIDE_WIN>
                  <AllowOptions val="N"/>
                  <AllowQuery val="Y"/>
                  <AllowModify val="Y"/>
                  <AllowCreate val="Y"/>
                  <AllowDelete val="Y"/>
                  <AllowLocate val="Y"/>
                  <AllowRange val="Y"/>
                  <AllowIndexChange val="Y"/>
                  <AllowSorting val="Y"/>
                  <AllowIOFiles val="Y"/>
                  <RecordCycle val="Y"/>
                  <AllowEvents val="Y"/>
                  <AllowIndexOptimization val="Y"/>
                  <AllowLocationInQuery val="Y"/>
                  <AllowPrintingData val="N"/>
                </SIDE_WIN>
                <WIN>
                  <OpenTaskWindow val="N"/>
                  <CloseTaskWindow val="Y"/>
                  <ForegroundWindow val="Y"/>
                  <FlipFld val="N"/>
                  <RefreshTaskWindow ReturnValue="N"/>
                </WIN>
                <BOX>
                  <Direction val="V"/>
                </BOX>
              </Information>
              <TaskLogic>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="M"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <_TotalVariabls val="1"/>
                  <_TotalVirtuals val="1"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <DATAVIEW_SRC Type="M">
                        <Condition val="N"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </DATAVIEW_SRC>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="F">
                        <ASS/>
                        <Column val="1"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Block SetParam RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="6"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="7"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Block SetParam RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="9"/>
                        <ReturnValue/>
                        <Condition Exp="8"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="10"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End SetParam XmlCnt RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="13"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=" **** Schema  Destination ****"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="14"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <CallTask>
                        <OperationType val="T"/>
                        <TaskID comp="-1" obj="1"/>
                        <Lock val="N"/>
                        <Arguments/>
                        <Wait val="Y"/>
                        <SyncData val="N"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </CallTask>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Temp SetParam TP   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="1"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="2"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="3"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Temp SetParam TP   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Temp SetParam TS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="4"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="5"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Temp SetParam TS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
              </TaskLogic>
              <TaskForms>
                <FormEntry _last_test_id="1">
                  <PropertyList model="FORM_GUI0">
                    <Width/>
                    <Height/>
                    <_Comment/>
                    <FormName valUnicode="Empty Program"/>
                  </PropertyList>
                </FormEntry>
              </TaskForms>
              <Expressions>
                <Expression val="1">
                  <ExpSyntax val="SetParam('Temp_3_S_1_20_228_2_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_20_228_2_Envelope/Body'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="2">
                  <ExpSyntax val="SetParam('Temp_XMLCnt_3_S_1_20_228_2_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_20_228_2_Envelope/Body'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="3">
                  <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body',0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="4">
                  <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body',GetParam('Temp_3_S_1_20_228_2_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="5">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_20_228_2_Envelope/Body',GetParam('Temp_XMLCnt_3_S_1_20_228_2_Envelope/Body_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="6">
                  <ExpSyntax val="GetParam('S_1_20_228_2_Envelope/Body')&gt;=GetParam('XMLCnt_S_1_20_228_2_Envelope/Body')"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="7">
                  <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body',0)"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="8">
                  <ExpSyntax val="GetParam('S_1_20_228_2_Envelope/Body') =0"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="9">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_20_228_2_Envelope/Body',XMLCnt(2,1,'/Envelope['&amp;Trim(Str(GetParam('S_1_20_228_2_Envelope'),''))&amp;']/Body'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="10">
                  <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body',GetParam('S_1_20_228_2_Envelope/Body')+1)"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="11">
                  <ExpSyntax val="GetParam('S_1_20_228_2_Envelope/Body')&gt;=GetParam('XMLCnt_S_1_20_228_2_Envelope/Body')"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="12">
                  <ExpSyntax val="(ExpCalc('11'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="13">
                  <ExpSyntax val="GetParam('XMLCnt_S_1_20_228_2_Envelope/Body')&gt;0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="14">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(C),'C','soap:Body','soap:Envelope/soap:Body','',B,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
              </Expressions>
              <Task>
                <Header Description="soap:Envelope/soap:Body/app1:runReport/app1:reportRequest">
                  <Public/>
                  <ExecutionRight/>
                  <Resident val="N"/>
                  <SQL val="N"/>
                  <ReturnValue>
                    <ReturnValueAttr/>
                    <ParametersAttributes/>
                  </ReturnValue>
                  <SqlWhereExist val="N"/>
                  <TaskType val="B"/>
                  <External val="Y"/>
                  <LastModified _date="738228" _time="67579" date="14//3//2022" time="18:46:19.6693063"/>
                </Header>
                <ReturnValueExpression/>
                <Resource>
                  <Columns>
                    <Column id="1" name="D_1_attributeFormat">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="2" name="D_1_flattenXML">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="3" name="D_1_reportAbsolutePath">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="4" name="D_1_sizeOfDataChunkDownload">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="5" name="RecordsExistIndication">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_LOGICAL"/>
                        <StoredAs val="15"/>
                        <Size val="28"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="5"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                  </Columns>
                </Resource>
                <Information>
                  <Key>
                    <Column/>
                    <Mode val="N"/>
                  </Key>
                  <DB/>
                  <Sort>
                    <CLS val="A"/>
                  </Sort>
                  <ForceRecordDelete DEL="N"/>
                  <EndTaskCondition val="Y" Exp="23"/>
                  <EvaluateEndCondition val="A"/>
                  <InitialMode val="M"/>
                  <Locate Direction="A"/>
                  <Range Direction="A"/>
                  <VarRange/>
                  <TaskProperties>
                    <SelectionTable val="N"/>
                    <ConfirmUpdate CNFU="N"/>
                    <ConfirmCancel val="N"/>
                    <ErrorStrategy val="R"/>
                    <LockingStrategy val="M"/>
                    <CacheStrategy val="T"/>
                    <ForceRecordSuffix val="N"/>
                    <TransactionMode val="P"/>
                    <TransactionBegin val="N"/>
                    <PreloadView val="N"/>
                    <KeepCreatedContext val="N"/>
                  </TaskProperties>
                  <SIDE_WIN>
                    <AllowOptions val="N"/>
                    <AllowQuery val="Y"/>
                    <AllowModify val="Y"/>
                    <AllowCreate val="Y"/>
                    <AllowDelete val="Y"/>
                    <AllowLocate val="Y"/>
                    <AllowRange val="Y"/>
                    <AllowIndexChange val="Y"/>
                    <AllowSorting val="Y"/>
                    <AllowIOFiles val="Y"/>
                    <RecordCycle val="Y"/>
                    <AllowEvents val="Y"/>
                    <AllowIndexOptimization val="Y"/>
                    <AllowLocationInQuery val="Y"/>
                    <AllowPrintingData val="N"/>
                  </SIDE_WIN>
                  <WIN>
                    <OpenTaskWindow val="N"/>
                    <CloseTaskWindow val="Y"/>
                    <ForegroundWindow val="Y"/>
                    <FlipFld val="N"/>
                    <RefreshTaskWindow ReturnValue="N"/>
                  </WIN>
                  <BOX>
                    <Direction val="V"/>
                  </BOX>
                </Information>
                <TaskLogic>
                  <LogicUnit id="4" propagate="78">
                    <Level val="R"/>
                    <Type val="M"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <_TotalVariabls val="5"/>
                    <_TotalVirtuals val="5"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <DATAVIEW_SRC Type="M">
                          <Condition val="N"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </DATAVIEW_SRC>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="G">
                          <ASS/>
                          <Column val="1"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="H">
                          <ASS/>
                          <Column val="2"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="I">
                          <ASS/>
                          <Column val="3"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="J">
                          <ASS/>
                          <Column val="4"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="K">
                          <ASS/>
                          <Column val="5"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="R"/>
                    <Type val="S"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***Begin Source Builder   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Loop Block SetParam RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                          <Condition Exp="11"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </BLOCK>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="12"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                          <Condition Exp="13"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </BLOCK>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="14"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <END_BLK/>
                      </LogicLine>
                      <LogicLine>
                        <END_BLK/>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Loop Block SetParam RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="16"/>
                          <ReturnValue/>
                          <Condition Exp="15"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="18"/>
                          <ReturnValue/>
                          <Condition Exp="17"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="19"/>
                          <ReturnValue/>
                          <Condition Exp="17"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="20"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End SetParam XmlCnt RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Loop Filter For Hole  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Loop Filter For Hole  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                          <Condition Exp="24"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </BLOCK>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***End Source Builder   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=" **** Schema  Destination ****"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="25"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***Begin Update Destination Vars   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="G"/>
                          <WithValue val="26"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="27"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="K"/>
                          <WithValue val="29"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition Exp="28"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="H"/>
                          <WithValue val="30"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="31"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="K"/>
                          <WithValue val="33"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition Exp="32"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="I"/>
                          <WithValue val="34"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="35"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="K"/>
                          <WithValue val="37"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition Exp="36"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="J"/>
                          <WithValue val="38"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="39"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="K"/>
                          <WithValue val="41"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition Exp="40"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***End Update Destination Vars   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <END_BLK/>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="R"/>
                    <Type val="P"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="T"/>
                    <Type val="P"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Temp SetParam TP   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="1"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="2"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="3"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="6"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="7"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="8"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Temp SetParam TP   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="T"/>
                    <Type val="S"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Temp SetParam TS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="4"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="5"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="9"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="10"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Temp SetParam TS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                </TaskLogic>
                <TaskForms>
                  <FormEntry _last_test_id="1">
                    <PropertyList model="FORM_GUI0">
                      <Width/>
                      <Height/>
                      <_Comment/>
                      <FormName valUnicode="Empty Program"/>
                    </PropertyList>
                  </FormEntry>
                </TaskForms>
                <Expressions>
                  <Expression val="1">
                    <ExpSyntax val="SetParam('Temp_4_S_1_20_228_2_Envelope/Body/runReport/reportRequest_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_20_228_2_Envelope/Body/runReport/reportRequest'))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="2">
                    <ExpSyntax val="SetParam('Temp_XMLCnt_4_S_1_20_228_2_Envelope/Body/runReport/reportRequest_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport/reportRequest'))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="3">
                    <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body/runReport/reportRequest',0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="4">
                    <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body/runReport/reportRequest',GetParam('Temp_4_S_1_20_228_2_Envelope/Body/runReport/reportRequest_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="5">
                    <ExpSyntax val="SetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport/reportRequest',GetParam('Temp_XMLCnt_4_S_1_20_228_2_Envelope/Body/runReport/reportRequest_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="6">
                    <ExpSyntax val="SetParam('Temp_4_S_1_20_228_2_Envelope/Body/runReport_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_20_228_2_Envelope/Body/runReport'))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="7">
                    <ExpSyntax val="SetParam('Temp_XMLCnt_4_S_1_20_228_2_Envelope/Body/runReport_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport'))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="8">
                    <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body/runReport',0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="9">
                    <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body/runReport',GetParam('Temp_4_S_1_20_228_2_Envelope/Body/runReport_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="10">
                    <ExpSyntax val="SetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport',GetParam('Temp_XMLCnt_4_S_1_20_228_2_Envelope/Body/runReport_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="11">
                    <ExpSyntax val="GetParam('S_1_20_228_2_Envelope/Body/runReport/reportRequest')&gt;=GetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport/reportRequest')"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="12">
                    <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body/runReport/reportRequest',0)"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="13">
                    <ExpSyntax val="GetParam('S_1_20_228_2_Envelope/Body/runReport')&gt;=GetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport')"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="14">
                    <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body/runReport',0)"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="15">
                    <ExpSyntax val="GetParam('S_1_20_228_2_Envelope/Body/runReport') =0"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="16">
                    <ExpSyntax val="SetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport',XMLCnt(3,1,'/Envelope['&amp;Trim(Str(GetParam('S_1_20_228_2_Envelope'),''))&amp;']/Body['&amp;Trim(Str(GetParam('S_1_20_228_2_Envelope/Body'),''))&amp;']/runReport'))"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="17">
                    <ExpSyntax val="GetParam('S_1_20_228_2_Envelope/Body/runReport/reportRequest') =0"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="18">
                    <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body/runReport',GetParam('S_1_20_228_2_Envelope/Body/runReport')+1)"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="19">
                    <ExpSyntax val="SetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport/reportRequest',XMLCnt(3,1,'/Envelope['&amp;Trim(Str(GetParam('S_1_20_228_2_Envelope'),''))&amp;']/Body['&amp;Trim(Str(GetParam('S_1_20_228_2_Envelope/Body'),''))&amp;']/runReport['&amp;Trim(Str(GetParam('S_1_20_228_2_Envelope/Body/runReport'),''))&amp;']/reportRequest'))"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="20">
                    <ExpSyntax val="SetParam('S_1_20_228_2_Envelope/Body/runReport/reportRequest',GetParam('S_1_20_228_2_Envelope/Body/runReport/reportRequest')+1)"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="21">
                    <ExpSyntax val="GetParam('S_1_20_228_2_Envelope/Body/runReport/reportRequest')&gt;=GetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport/reportRequest')"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="22">
                    <ExpSyntax val="GetParam('S_1_20_228_2_Envelope/Body/runReport')&gt;=GetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport')"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="23">
                    <ExpSyntax val="(ExpCalc('21'EXP)  AND ExpCalc('22'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="24">
                    <ExpSyntax val="GetParam('XMLCnt_S_1_20_228_2_Envelope/Body/runReport/reportRequest')&gt;0"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="25">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(C),'C','app1:reportRequest','soap:Envelope/soap:Body/app1:runReport/app1:reportRequest','',B,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="26">
                    <ExpSyntax val="xmlget(3,1,'/Envelope['&amp;trim(str(getparam('S_1_20_228_2_Envelope'),''))&amp;']'&amp;'/Body['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body'),''))&amp;']'&amp;'/runReport['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body/runReport'),''))&amp;']'&amp;'/reportRequest['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body/runReport/reportRequest'),''))&amp;']'&amp;'/attributeFormat','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="27">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(C),'S','app1:attributeFormat','soap:Envelope/soap:Body/app1:runReport/app1:reportRequest/app1:attributeFormat',rtrim(G),B,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="28">
                    <ExpSyntax val="NOT(K)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="29">
                    <ExpSyntax val="'True'Log"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="30">
                    <ExpSyntax val="xmlget(3,1,'/Envelope['&amp;trim(str(getparam('S_1_20_228_2_Envelope'),''))&amp;']'&amp;'/Body['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body'),''))&amp;']'&amp;'/runReport['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body/runReport'),''))&amp;']'&amp;'/reportRequest['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body/runReport/reportRequest'),''))&amp;']'&amp;'/flattenXML','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="31">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(C),'S','app1:flattenXML','soap:Envelope/soap:Body/app1:runReport/app1:reportRequest/app1:flattenXML',rtrim(H),B,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="32">
                    <ExpSyntax val="NOT(K)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="33">
                    <ExpSyntax val="'True'Log"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="34">
                    <ExpSyntax val="xmlget(3,1,'/Envelope['&amp;trim(str(getparam('S_1_20_228_2_Envelope'),''))&amp;']'&amp;'/Body['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body'),''))&amp;']'&amp;'/runReport['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body/runReport'),''))&amp;']'&amp;'/reportRequest['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body/runReport/reportRequest'),''))&amp;']'&amp;'/reportAbsolutePath','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="35">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(C),'S','app1:reportAbsolutePath','soap:Envelope/soap:Body/app1:runReport/app1:reportRequest/app1:reportAbsolutePath',rtrim(I),B,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="36">
                    <ExpSyntax val="NOT(K)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="37">
                    <ExpSyntax val="'True'Log"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="38">
                    <ExpSyntax val="xmlget(3,1,'/Envelope['&amp;trim(str(getparam('S_1_20_228_2_Envelope'),''))&amp;']'&amp;'/Body['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body'),''))&amp;']'&amp;'/runReport['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body/runReport'),''))&amp;']'&amp;'/reportRequest['&amp;trim(str(getparam('S_1_20_228_2_Envelope/Body/runReport/reportRequest'),''))&amp;']'&amp;'/sizeOfDataChunkDownload','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="39">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(C),'S','app1:sizeOfDataChunkDownload','soap:Envelope/soap:Body/app1:runReport/app1:reportRequest/app1:sizeOfDataChunkDownload',rtrim(J),B,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="40">
                    <ExpSyntax val="NOT(K)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="41">
                    <ExpSyntax val="'True'Log"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                </Expressions>
              </Task>
            </Task>
          </Task>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
